export class Employee {
    constructor(
        public id: number,
        public employeeId: string,
        public email: string,
        public fkAddressId: number,
        public fkOtherDetailsId: number,
        public fkProjectId: number,
        public fkDesignation: number,
        public fkCompetency: number,
        public fkDepartment: number,
        public fkReportingManager: number,
        public fkManager: number,
        // public fkSbuHead: number,
        public fkParentId: number,
        public fkParentIdCount: number,
        public fkApprovalTemplateId: number,
        public fkPayroll: number,
        public firstName: string,
        public middleName: string,
        public lastName: string,
        public imgUrl: string,
        public designation: string,
        public baseLocation: string,
        public description: string,
        public interviwer: number,
        public joiningDate: string,
        public redirectUrl: string,
        public createdBy: number,
        public createdDate: string,
        public modifiedBy: number,
        public modifiedDate: string,
        public isActive: boolean,
        public fkProfileId: number,
        public fkSbuId: number,
        public fkRoleId: number
) { }
}
