import { SbuMaster } from "./sbuMaster.model";
export class EmployeeMaster {
    id: number;
    employeeId: string;
    email: string;
    fkAddressId: number | null;
    fkOtherDetailsId: number | null;
    fkProjectId: number | null;
    fkDesignation: number | null;
    fkCompetency: number | null;
    fkDepartment: number | null;
    fkReportingManager: number | null;
    fkManager: number | null;
    fkSbuId: number | null;
    fkParentId: number | null;
    fkParentIdCount: number | null;
    fkApprovalTemplateId: number | null;
    fkPayroll: number | null;
    fkProfileId: number | null;
    baseLocation: string;
    description: string;
    firstName: string;
    middleName: string;
    lastName: string;
    imgUrl: string;
    designation: string;
    interviwer: number | null;
    joiningDate: string | null;
    redirectUrl: string;
    createdBy: number | null;
    createdDate: string | null;
    modifiedBy: number | null;
    modifiedDate: string | null;
    isActive: boolean | null;
    fkRoleId: number | null;
    dol: string | null;
    dob: string | null;
    department: string;
    location: string;
    reportingManagerName: string;
    reportingManagerEmpId: string;
    managerName: string;
    managerEmpId: string;
    category: string;
    paygroup: string;
    role: string;
    sbuMasterViewModel: SbuMaster;
    fullName: string;
    payGroup: string;
    pernr: string;
    desigRoleId: number;
    hrEmployeeId: number;
    profileIDs: string;
    totalCount: number;
    totalPages: number;
}