export class GateInwardMaster{
    constructor(
        public id: number,
        public mandt: string,
        public fiN_YEAR: string,
        public planT_ID: string,
        public gI_GATENO: string,
        public gI_NO: number,
        public gO_NO: number,
        public gI_TYPE: string,
        public gI_DATE: string,
        public gO_FIN_YEAR: string,
        public lifnr: string,
        public namE1: string,
        public orT01: string,
        public regio: string,
        public vehicleno: string,
        public iN_TIME: string,
        public persoN_NAME: string,
        public doC_NO: string,
        public doC_DATE: string,
        public deL_FLG: string,
        public deL_REASON: string,
        public createD_BY: string,
        public createD_DATE: string,
        public modifieD_BY: string,
        public modifieD_DATE: string,
        public deleteD_BY: string,
        public deleteD_DATE: string,
        public remarks: string,
        public isActive: boolean,
        public recid: string
    ){}
}