export class GateInwardDependent{
    constructor(
        public id: number,
        public mandt: string,
        public fiN_YEAR: string,
        public planT_ID: string,
        public gI_GATENO: string,
        public gI_NO: number,
        public iteM_NO: number,
        public iteM_CODE: string,
        public materiaL_TYPE: string,
        public iteM_DESC: string,
        public uom: string,
        public nO_OF_CASES: number,
        public qty: number,
        public iN_ITEM_DESC: string,
        public iN_QTY: number,
        public scraP_QTY: number,
        public qtY_RCVD: number,
        public pO_NO: string,
        public pO_DATE: string,
        public mblnr: string,
        public mjahr: string,
        public zeile: string,
        public deL_FLG: string,
        public createD_BY: string,
        public createD_DATE: string,
        public modifieD_BY: string,
        public modifieD_DATE: string,
        public deleteD_BY: string,
        public deleteD_DATE: string,
        public isActive: boolean,
        public fkgatE_ENTRY_M: number,

        public iteM_CODE_P: string,
        public iteM_DESC_P: string,
        public remainQTY:number,
        public qtY_Rcvd: number
    ){}
}