export interface TaskModel{
    selected: boolean;
    flowTaskId: number;
    flowId: number;
    flowType: string
    objectId: number;
    objectType: string
    name: string
    employeeNo: string
    description: string
    initiatedBy: string
    startDate: string
    activityTrace: string
    role: string
    firstName: string
    middleName: string
    lastName: string
    plantCode: string
    plant: string
    payGroup: string
    employeeCategory: string
    location: string
    jobRole: string
    designation: string
    offeredSalary: number;
    approvers: string[];
    employeeId: number;
    appraisalEffectiveDate: string
    appraisalSalaryProcessingDate: string
    appraisalNextRevisionDate: string
    appraisalType: string
    appraisalOldCTC: number;
    appraisalNewCTC: number;
    appraisalOneTimeAmount: number;
    appraisalIncrementAmount: number;
}