export class LeaveDetails {
    id!: number;
  userId: string
  leaveType: string
  startDate: string
  endDate: string
  startDuration: string
  endDuration: string
  noOfDays: string
  leaveStatus: string
  recordStatus: string
  departmentId!: number;
  countryId!: number;
  stateId!: number;
  plantId!: number;
  designationId!: number;
  documents: string
  submitDate: string
  reasonType: string
  reason: string
  firstname: string
  approverId: string
  approvelStatus: string
  forwardedEmpId: string
  lastApprover: string
  pendingApprover: string
  reqId: string
  approvedDate: string
  rejectedDate: string
  lvBalence!: number;
  hrId!: number;
  sapStatus: string
  sapApprovedDate: string
  sapMessage: string
  sapAppStatus: string
  cancelflag!: number;
  year: string
}