import { Component, OnInit } from '@angular/core';
import { HttpService } from '../../../shared/http-service';
import { APIURLS } from '../../../shared/api-url';
import { Router, RouterModule } from '@angular/router';
import { ExcelService } from '../../../shared/excel-service';
import { AuthData } from '../../../auth/auth.model';
import { EmailTemplateFilter } from './email-template-filter.model'
import { EmailTemplate } from './email-template.model';
import { AngularEditorConfig } from '@kolkov/angular-editor';
import { Util } from '../../Services/util.service';

declare var $: any;
declare var toastr: any;

@Component({
  selector: 'app-email-templates',
  templateUrl: './email-templates.component.html',
  styleUrls: ['./email-templates.component.css'],
  providers: [Util]
})
export class EmailTemplatesComponent implements OnInit {
  id: number = 0;
  action: string;
  isLoading: boolean = false;
  filterData: any = {};
  currentUser: AuthData;  
  filterModel: EmailTemplateFilter = {} as EmailTemplateFilter;
  emailTemplateList: any[] = [];  
  item: any = {};
  editIndex : number = -1;
  editorConfig: AngularEditorConfig = {
    editable: true,
    spellcheck: true,
    height: 'auto',
    minHeight: '300px',
    maxHeight: 'auto',
    width: 'auto',
    enableToolbar: true,
    showToolbar: true,
    placeholder: 'Enter text here...',
    sanitize: true,
    toolbarPosition: 'top',
};
regardsConfig: AngularEditorConfig = {
  editable: true,
  spellcheck: true,
  height: 'auto',
  minHeight: '50px',
  maxHeight: '100px',
  width: 'auto',
  enableToolbar: true,
  showToolbar: true,
  placeholder: 'Enter text here...',
  sanitize: true,
  toolbarPosition: 'top',
};

statusList = [
  { type: "No", color:"danger"},
  { type: "Yes", color:"success" } ]

  isActive = [
    { type: "Yes" , value :"true" },
    { type: "No" , value :"false"}];

    keywordsList = [];

    keywordsFullList = [
      {emailType:"Offer-Email", keyword: "DESIGNATION" , description :"" },
      {emailType:"Offer-Email", keyword: "PAY_GROUP" , description :"" },
      {emailType:"Offer-Email", keyword: "LOCATION" , description :"" },
      {emailType:"Offer-Email", keyword: "RECEIVER" , description :"" },
      {emailType:"Offer-Email", keyword: "TITLE" , description :"" },
      {emailType:"Offer-Email", keyword: "OFFER_NO" , description :"" },
      {emailType:"Offer-Email", keyword: "OFFER_DATE" , description :"" },
      {emailType:"Offer-Email", keyword: "CANDIDATE_NAME" , description :"" },
      {emailType:"Offer-Email", keyword: "MOBILE_NO" , description :"" },
      {emailType:"Offer-Email", keyword: "EMAIL_ID" , description :"" },
      {emailType:"Offer-Email", keyword: "JOINING_DATE" , description :"" },
      {emailType:"Offer-Email", keyword: "CREATED_BY" , description :"" },
      {emailType:"Offer-Email", keyword: "ACCEPTANCE_URL" , description :"" },
      {emailType:"Offer-Email", keyword: "OFFER_APPROVAL_SEND_URL" , description :"" },
      {emailType:"Offer-Email", keyword: "REASON" , description :"Reason for Withdrawal/Rejection by Approver" },
      {emailType:"1stLevelApproval", keyword: "EMPLOYEE", description :"" },
        {emailType:"1stLevelApproval", keyword: "FROMTIME", description :"" },
        {emailType:"1stLevelApproval", keyword: "LOCATION", description :"" },
        {emailType:"1stLevelApproval", keyword: "PURPOSE", description :"" },
        {emailType:"1stLevelApproval", keyword: "REQUESTNO", description :"" },
        {emailType:"1stLevelApproval", keyword: "ROOMNAME", description :"" },
        {emailType:"1stLevelApproval", keyword: "TOTIME", description :"" },
        {emailType:"2ndLevelApproval", keyword: "EMPLOYEE", description :"" },
        {emailType:"2ndLevelApproval", keyword: "FROMTIME", description :"" },
        {emailType:"2ndLevelApproval", keyword: "LOCATION", description :"" },
        {emailType:"2ndLevelApproval", keyword: "MANAGER", description :"" },
        {emailType:"2ndLevelApproval", keyword: "MANAGERCOMMENTS", description :"" },
        {emailType:"2ndLevelApproval", keyword: "PURPOSE", description :"" },
        {emailType:"2ndLevelApproval", keyword: "REQUESTNO", description :"" },
        {emailType:"2ndLevelApproval", keyword: "ROOMNAME", description :"" },
        {emailType:"2ndLevelApproval", keyword: "TOTIME", description :"" },
        {emailType:"MeetingApproved", keyword: "ADMINCOMMENTS", description :"" },
        {emailType:"MeetingApproved", keyword: "EMPLOYEE", description :"" },
        {emailType:"MeetingApproved", keyword: "FROMTIME", description :"" },
        {emailType:"MeetingApproved", keyword: "LOCATION", description :"" },
        {emailType:"MeetingApproved", keyword: "MANAGERCOMMENTS", description :"" },
        {emailType:"MeetingApproved", keyword: "PURPOSE", description :"" },
        {emailType:"MeetingApproved", keyword: "ROOMNAME", description :"" },
        {emailType:"MeetingApproved", keyword: "TOTIME", description :"" },
        {emailType:"MeetingRejected", keyword: "ADMINCOMMENTS", description :"" },
        {emailType:"MeetingRejected", keyword: "EMPLOYEE", description :"" },
        {emailType:"MeetingRejected", keyword: "FROMTIME", description :"" },
        {emailType:"MeetingRejected", keyword: "LOCATION", description :"" },
        {emailType:"MeetingRejected", keyword: "MANAGERCOMMENTS", description :"" },
        {emailType:"MeetingRejected", keyword: "PURPOSE", description :"" },
        {emailType:"MeetingRejected", keyword: "ROOMNAME", description :"" },
        {emailType:"MeetingRejected", keyword: "TOTIME", description :"" },
        {emailType:"Cab-1stLevelApproval", keyword: "EMPLOYEE", description :"" },
        {emailType:"Cab-1stLevelApproval", keyword: "FROMLOCATION", description :"" },
        {emailType:"Cab-1stLevelApproval", keyword: "FROMTIME", description :"" },
        {emailType:"Cab-1stLevelApproval", keyword: "PURPOSE", description :"" },
        {emailType:"Cab-1stLevelApproval", keyword: "REQUESTNO", description :"" },
        {emailType:"Cab-1stLevelApproval", keyword: "SERVICETYPE", description :"" },
        {emailType:"Cab-1stLevelApproval", keyword: "TOLOCATION", description :"" },
        {emailType:"Cab-1stLevelApproval", keyword: "TOTIME", description :"" },
        {emailType:"Cab-1stLevelApproval", keyword: "TRIPTYPE", description :"" },
        {emailType:"Cab-2ndLevelApproval", keyword: "EMPLOYEE", description :"" },
        {emailType:"Cab-2ndLevelApproval", keyword: "FROMLOCATION", description :"" },
        {emailType:"Cab-2ndLevelApproval", keyword: "FROMTIME", description :"" },
        {emailType:"Cab-2ndLevelApproval", keyword: "MANAGER", description :"" },
        {emailType:"Cab-2ndLevelApproval", keyword: "MANAGERCOMMENTS", description :"" },
        {emailType:"Cab-2ndLevelApproval", keyword: "PURPOSE", description :"" },
        {emailType:"Cab-2ndLevelApproval", keyword: "REQUESTNO", description :"" },
        {emailType:"Cab-2ndLevelApproval", keyword: "SERVICETYPE", description :"" },
        {emailType:"Cab-2ndLevelApproval", keyword: "TOLOCATION", description :"" },
        {emailType:"Cab-2ndLevelApproval", keyword: "TOTIME", description :"" },
        {emailType:"Cab-2ndLevelApproval", keyword: "TRIPTYPE", description :"" },
        {emailType:"CabRequestApproved", keyword: "ADMINCOMMENTS", description :"" },
        {emailType:"CabRequestApproved", keyword: "CABDETAILS", description :"" },
        {emailType:"CabRequestApproved", keyword: "DRIVER", description :"" },
        {emailType:"CabRequestApproved", keyword: "DRIVERCONTACT", description :"" },
        {emailType:"CabRequestApproved", keyword: "EMPLOYEE", description :"" },
        {emailType:"CabRequestApproved", keyword: "FROMLOCATION", description :"" },
        {emailType:"CabRequestApproved", keyword: "FROMTIME", description :"" },
        {emailType:"CabRequestApproved", keyword: "MANAGERCOMMENTS", description :"" },
        {emailType:"CabRequestApproved", keyword: "PURPOSE", description :"" },
        {emailType:"CabRequestApproved", keyword: "SERVICETYPE", description :"" },
        {emailType:"CabRequestApproved", keyword: "TOLOCATION", description :"" },
        {emailType:"CabRequestApproved", keyword: "TOTIME", description :"" },
        {emailType:"CabRequestApproved", keyword: "TRIPTYPE", description :"" },
        {emailType:"CabRequestRejected", keyword: "ADMINCOMMENTS", description :"" },
        {emailType:"CabRequestRejected", keyword: "EMPLOYEE", description :"" },
        {emailType:"CabRequestRejected", keyword: "FROMLOCATION", description :"" },
        {emailType:"CabRequestRejected", keyword: "FROMTIME", description :"" },
        {emailType:"CabRequestRejected", keyword: "MANAGERCOMMENTS", description :"" },
        {emailType:"CabRequestRejected", keyword: "PURPOSE", description :"" },
        {emailType:"CabRequestRejected", keyword: "SERVICETYPE", description :"" },
        {emailType:"CabRequestRejected", keyword: "TOLOCATION", description :"" },
        {emailType:"CabRequestRejected", keyword: "TOTIME", description :"" },
        {emailType:"CabRequestRejected", keyword: "TRIPTYPE", description :"" },
        {emailType:"GH-1stLevelApproval", keyword: "EMPLOYEE", description :"" },
        {emailType:"GH-1stLevelApproval", keyword: "FROMTIME", description :"" },
        {emailType:"GH-1stLevelApproval", keyword: "LOCATION", description :"" },
        {emailType:"GH-1stLevelApproval", keyword: "PURPOSE", description :"" },
        {emailType:"GH-1stLevelApproval", keyword: "REQUESTNO", description :"" },
        {emailType:"GH-1stLevelApproval", keyword: "ROOMNAME", description :"" },
        {emailType:"GH-1stLevelApproval", keyword: "TOTIME", description :"" },
        {emailType:"GHMeetingApproved", keyword: "ADMINCOMMENTS", description :"" },
        {emailType:"GHMeetingApproved", keyword: "EMPLOYEE", description :"" },
        {emailType:"GHMeetingApproved", keyword: "FROMTIME", description :"" },
        {emailType:"GHMeetingApproved", keyword: "LOCATION", description :"" },
        {emailType:"GHMeetingApproved", keyword: "MANAGERCOMMENTS", description :"" },
        {emailType:"GHMeetingApproved", keyword: "PURPOSE", description :"" },
        {emailType:"GHMeetingApproved", keyword: "ROOMNAME", description :"" },
        {emailType:"GHMeetingApproved", keyword: "TOTIME", description :"" },
        {emailType:"GHMeetingRejected", keyword: "ADMINCOMMENTS", description :"" },
        {emailType:"GHMeetingRejected", keyword: "EMPLOYEE", description :"" },
        {emailType:"GHMeetingRejected", keyword: "FROMTIME", description :"" },
        {emailType:"GHMeetingRejected", keyword: "LOCATION", description :"" },
        {emailType:"GHMeetingRejected", keyword: "MANAGERCOMMENTS", description :"" },
        {emailType:"GHMeetingRejected", keyword: "PURPOSE", description :"" },
        {emailType:"GHMeetingRejected", keyword: "ROOMNAME", description :"" },
        {emailType:"GHMeetingRejected", keyword: "TOTIME", description :"" },
        {emailType:"Rejected", keyword: "MATERIALNAME", description :"" },
        {emailType:"Rejected", keyword: "MATERIALTYPE", description :"" },
        {emailType:"Rejected", keyword: "PLANT", description :"" },
        {emailType:"Rejected", keyword: "REQUESTEDON", description :"" },
        {emailType:"Rejected", keyword: "REQUESTNO", description :"" },
        {emailType:"Rejected", keyword: "STATUS", description :"" },
        {emailType:"Created", keyword: "MATERIALNAME", description :"" },
        {emailType:"Created", keyword: "MATERIALTYPE", description :"" },
        {emailType:"Created", keyword: "PLANT", description :"" },
        {emailType:"Created", keyword: "REQUESTEDON", description :"" },
        {emailType:"Created", keyword: "REQUESTNO", description :"" },
        {emailType:"Created", keyword: "SAPCODEEXIST", description :"" },
        {emailType:"Created", keyword: "SAPCODEEXISTCOAT", description :"" },
        {emailType:"Created", keyword: "SAPCODENO", description :"" },
        {emailType:"Created", keyword: "SAPCODENOCOAT", description :"" },
        {emailType:"Created", keyword: "STATUS", description :"" },
        {emailType:"ReverttoLastApprover", keyword: "MATERIALNAME", description :"" },
        {emailType:"ReverttoLastApprover", keyword: "MATERIALTYPE", description :"" },
        {emailType:"ReverttoLastApprover", keyword: "PLANT", description :"" },
        {emailType:"ReverttoLastApprover", keyword: "REQUESTEDON", description :"" },
        {emailType:"ReverttoLastApprover", keyword: "REQUESTNO", description :"" },
        {emailType:"ReverttoInitiator", keyword: "MATERIALNAME", description :"" },
        {emailType:"ReverttoInitiator", keyword: "MATERIALTYPE", description :"" },
        {emailType:"ReverttoInitiator", keyword: "PLANT", description :"" },
        {emailType:"ReverttoInitiator", keyword: "REQUESTEDON", description :"" },
        {emailType:"ReverttoInitiator", keyword: "REQUESTNO", description :"" },
        {emailType:"InProcess", keyword: "MATERIALNAME", description :"" },
        {emailType:"InProcess", keyword: "MATERIALTYPE", description :"" },
        {emailType:"InProcess", keyword: "REQUESTEDON", description :"" },
        {emailType:"InProcess", keyword: "REQUESTNO", description :"" },
        {emailType:"InProcess", keyword: "REVIEWEDBY", description :"" },
        {emailType:"InProcess", keyword: "STATUS", description :"" },
        {emailType:"VM-Rejected", keyword: "CITY", description :"" },
        {emailType:"VM-Rejected", keyword: "Name", description :"" },
        {emailType:"VM-Rejected", keyword: "PLANT", description :"" },
        {emailType:"VM-Rejected", keyword: "REQUESTEDON", description :"" },
        {emailType:"VM-Rejected", keyword: "REQUESTNO", description :"" },
        {emailType:"VM-Rejected", keyword: "STATUS", description :"" },
        {emailType:"VM-Created", keyword: "CITY", description :"" },
        {emailType:"VM-Created", keyword: "Name", description :"" },
        {emailType:"VM-Created", keyword: "PLANT", description :"" },
        {emailType:"VM-Created", keyword: "REQUESTEDON", description :"" },
        {emailType:"VM-Created", keyword: "REQUESTNO", description :"" },
        {emailType:"VM-Created", keyword: "SAPCODEEXIST", description :"" },
        {emailType:"VM-Created", keyword: "SAPCODENO", description :"" },
        {emailType:"VM-Created", keyword: "STATUS", description :"" },
        {emailType:"VM-ReverttoLastApprover", keyword: "CITY", description :"" },
        {emailType:"VM-ReverttoLastApprover", keyword: "Name", description :"" },
        {emailType:"VM-ReverttoLastApprover", keyword: "PLANT", description :"" },
        {emailType:"VM-ReverttoLastApprover", keyword: "REQUESTEDON", description :"" },
        {emailType:"VM-ReverttoLastApprover", keyword: "REQUESTNO", description :"" },
        {emailType:"VM-ReverttoInitiator", keyword: "CITY", description :"" },
        {emailType:"VM-ReverttoInitiator", keyword: "Name", description :"" },
        {emailType:"VM-ReverttoInitiator", keyword: "PLANT", description :"" },
        {emailType:"VM-ReverttoInitiator", keyword: "REQUESTEDON", description :"" },
        {emailType:"VM-ReverttoInitiator", keyword: "REQUESTNO", description :"" },
        {emailType:"VM-InProcess", keyword: "CITY", description :"" },
        {emailType:"VM-InProcess", keyword: "Name", description :"" },
        {emailType:"VM-InProcess", keyword: "REQUESTEDON", description :"" },
        {emailType:"VM-InProcess", keyword: "REQUESTNO", description :"" },
        {emailType:"VM-InProcess", keyword: "REVIEWEDBY", description :"" },
        {emailType:"VM-InProcess", keyword: "STATUS", description :"" },{emailType:"CM-Rejected", keyword: "CITY", description :"" },
        {emailType:"CM-Rejected", keyword: "Name", description :"" },
        {emailType:"CM-Rejected", keyword: "REQUESTEDON", description :"" },
        {emailType:"CM-Rejected", keyword: "REQUESTNO", description :"" },
        {emailType:"CM-Rejected", keyword: "STATUS", description :"" },
        {emailType:"CM-Created", keyword: "CITY", description :"" },
        {emailType:"CM-Created", keyword: "Name", description :"" },
        {emailType:"CM-Created", keyword: "REQUESTEDON", description :"" },
        {emailType:"CM-Created", keyword: "REQUESTNO", description :"" },
        {emailType:"CM-Created", keyword: "SAPCODEEXIST", description :"" },
        {emailType:"CM-Created", keyword: "SAPCODENO", description :"" },
        {emailType:"CM-Created", keyword: "STATUS", description :"" },
        {emailType:"CM-ReverttoLastApprover", keyword: "CITY", description :"" },
        {emailType:"CM-ReverttoLastApprover", keyword: "Name", description :"" },
        {emailType:"CM-ReverttoLastApprover", keyword: "REQUESTEDON", description :"" },
        {emailType:"CM-ReverttoLastApprover", keyword: "REQUESTNO", description :"" },
        {emailType:"CM-ReverttoInitiator", keyword: "CITY", description :"" },
        {emailType:"CM-ReverttoInitiator", keyword: "Name", description :"" },
        {emailType:"CM-ReverttoInitiator", keyword: "REQUESTEDON", description :"" },
        {emailType:"CM-ReverttoInitiator", keyword: "REQUESTNO", description :"" },
        {emailType:"CM-InProcess", keyword: "CITY", description :"" },
        {emailType:"CM-InProcess", keyword: "Name", description :"" },
        {emailType:"CM-InProcess", keyword: "REQUESTEDON", description :"" },
        {emailType:"CM-InProcess", keyword: "REQUESTNO", description :"" },
        {emailType:"CM-InProcess", keyword: "REVIEWEDBY", description :"" },
        {emailType:"CM-InProcess", keyword: "STATUS", description :"" },
        {emailType:"SM-Rejected", keyword: "PLANT", description :"" },
        {emailType:"SM-Rejected", keyword: "REQUESTEDON", description :"" },
        {emailType:"SM-Rejected", keyword: "REQUESTNO", description :"" },
        {emailType:"SM-Rejected", keyword: "SERVICECAT", description :"" },
        {emailType:"SM-Rejected", keyword: "SERVICEDESC", description :"" },
        {emailType:"SM-Rejected", keyword: "STATUS", description :"" },
        {emailType:"SM-Created", keyword: "PLANT", description :"" },
        {emailType:"SM-Created", keyword: "REQUESTEDON", description :"" },
        {emailType:"SM-Created", keyword: "REQUESTNO", description :"" },
        {emailType:"SM-Created", keyword: "SAPCODEEXIST", description :"" },
        {emailType:"SM-Created", keyword: "SAPCODENO", description :"" },
        {emailType:"SM-Created", keyword: "SERVICECAT", description :"" },
        {emailType:"SM-Created", keyword: "SERVICEDESC", description :"" },
        {emailType:"SM-Created", keyword: "STATUS", description :"" },
        {emailType:"SM-ReverttoLastApprover", keyword: "PLANT", description :"" },
        {emailType:"SM-ReverttoLastApprover", keyword: "REQUESTEDON", description :"" },
        {emailType:"SM-ReverttoLastApprover", keyword: "REQUESTNO", description :"" },
        {emailType:"SM-ReverttoLastApprover", keyword: "SERVICECAT", description :"" },
        {emailType:"SM-ReverttoLastApprover", keyword: "SERVICEDESC", description :"" },
        {emailType:"Pending", keyword: "MATERIALNAME", description :"" },
        {emailType:"Pending", keyword: "MATERIALTYPE", description :"" },
        {emailType:"Pending", keyword: "REQUESTEDON", description :"" },
        {emailType:"Pending", keyword: "REQUESTNO", description :"" },
        {emailType:"Pending", keyword: "STATUS", description :"" },
        {emailType:"CustomerPending", keyword: "CITY", description :"" },
        {emailType:"CustomerPending", keyword: "Name", description :"" },
        {emailType:"CustomerPending", keyword: "REQUESTEDBY", description :"" },
        {emailType:"CustomerPending", keyword: "REQUESTEDON", description :"" },
        {emailType:"CustomerPending", keyword: "REQUESTNO", description :"" },
        {emailType:"CustomerPending", keyword: "STATUS", description :"" },
        {emailType:"VendorPending", keyword: "CITY", description :"" },
        {emailType:"VendorPending", keyword: "Name", description :"" },
        {emailType:"VendorPending", keyword: "REQUESTEDBY", description :"" },
        {emailType:"VendorPending", keyword: "REQUESTEDON", description :"" },
        {emailType:"VendorPending", keyword: "REQUESTNO", description :"" },
        {emailType:"VendorPending", keyword: "STATUS", description :"" },
        {emailType:"ServicePending", keyword: "REQUESTEDBY", description :"" },
        {emailType:"ServicePending", keyword: "REQUESTEDON", description :"" },
        {emailType:"ServicePending", keyword: "REQUESTNO", description :"" },
        {emailType:"ServicePending", keyword: "SERVICECAT", description :"" },
        {emailType:"ServicePending", keyword: "SERVICEDESC", description :"" },
        {emailType:"ServicePending", keyword: "STATUS", description :"" },
        {emailType:"EPending", keyword: "FROMPLANT", description :"" },
        {emailType:"EPending", keyword: "FROMSTOLOC", description :"" },
        {emailType:"EPending", keyword: "MATERIALTYPE", description :"" },
        {emailType:"EPending", keyword: "REQUESTEDON", description :"" },
        {emailType:"EPending", keyword: "REQUESTNO", description :"" },
        {emailType:"EPending", keyword: "SAPCODENO", description :"" },
        {emailType:"EPending", keyword: "STATUS", description :"" },
        {emailType:"EPending", keyword: "TOPLANT", description :"" },
        {emailType:"EPending", keyword: "TOSTOLOC", description :"" },
        {emailType:"ERejected", keyword: "FROMPLANT", description :"" },
        {emailType:"ERejected", keyword: "FROMSTOLOC", description :"" },
        {emailType:"ERejected", keyword: "MATERIALTYPE", description :"" },
        {emailType:"ERejected", keyword: "REQUESTEDON", description :"" },
        {emailType:"ERejected", keyword: "REQUESTNO", description :"" },
        {emailType:"ERejected", keyword: "SAPCODENO", description :"" },
        {emailType:"ERejected", keyword: "TOPLANT", description :"" },
        {emailType:"ERejected", keyword: "TOSTOLOC", description :"" },
        {emailType:"ECreated", keyword: "FROMPLANT", description :"" },
        {emailType:"ECreated", keyword: "FROMSTOLOC", description :"" },
        {emailType:"ECreated", keyword: "MATERIALTYPE", description :"" },
        {emailType:"ECreated", keyword: "REQUESTEDON", description :"" },
        {emailType:"ECreated", keyword: "REQUESTNO", description :"" },
        {emailType:"ECreated", keyword: "SAPCODENO", description :"" },
        {emailType:"ECreated", keyword: "TOPLANT", description :"" },
        {emailType:"ECreated", keyword: "TOSTOLOC", description :"" },
        {emailType:"EInProcess", keyword: "FROMPLANT", description :"" },
        {emailType:"EInProcess", keyword: "FROMSTOLOC", description :"" },
        {emailType:"EInProcess", keyword: "REQUESTEDON", description :"" },
        {emailType:"EInProcess", keyword: "REQUESTNO", description :"" },
        {emailType:"EInProcess", keyword: "SAPCODENO", description :"" },
        {emailType:"EInProcess", keyword: "TOPLANT", description :"" },
        {emailType:"EInProcess", keyword: "TOSTOLOC", description :"" },
        {emailType:"Ra_Request", keyword: "COUNTRY", description :"" },
        {emailType:"Ra_Request", keyword: "DOCUMENTS", description :"" },
        {emailType:"Ra_Request", keyword: "EMPLOYEE", description :"" },
        {emailType:"Ra_Request", keyword: "PURPOSE", description :"" },
        {emailType:"Ra_Request", keyword: "REQUESTNO", description :"" },
        {emailType:"Ra_Request", keyword: "ROOMNAME", description :"" },
        {emailType:"Ra_Provide", keyword: "COUNTRY", description :"" },
        {emailType:"Ra_Provide", keyword: "DOCUMENTS", description :"" },
        {emailType:"Ra_Provide", keyword: "EMPLOYEE", description :"" },
        {emailType:"Ra_Provide", keyword: "PURPOSE", description :"" },
        {emailType:"Ra_Provide", keyword: "REQUESTNO", description :"" },
        {emailType:"Ra_Provide", keyword: "ROOMNAME", description :"" },
        {emailType:"Ra_Reject", keyword: "COUNTRY", description :"" },
        {emailType:"Ra_Reject", keyword: "DOCUMENTS", description :"" },
        {emailType:"Ra_Reject", keyword: "EMPLOYEE", description :"" },
        {emailType:"Ra_Reject", keyword: "PURPOSE", description :"" },
        {emailType:"Ra_Reject", keyword: "REQUESTNO", description :"" },
        {emailType:"Ra_Reject", keyword: "ROOMNAME", description :"" },
        {emailType:"Ra_Approve", keyword: "COUNTRY", description :"" },
        {emailType:"Ra_Approve", keyword: "DOCUMENTS", description :"" },
        {emailType:"Ra_Approve", keyword: "EMPLOYEE", description :"" },
        {emailType:"Ra_Approve", keyword: "PURPOSE", description :"" },
        {emailType:"Ra_Approve", keyword: "REQUESTNO", description :"" },
        {emailType:"Ra_Approve", keyword: "ROOMNAME", description :"" },
        {emailType:"NPD", keyword: "REQUESTNO", description :"" },
        {emailType:"MPending", keyword: "DESC", description :"" },
        {emailType:"MPending", keyword: "REQUESTEDON", description :"" },
        {emailType:"MPending", keyword: "REQUESTNO", description :"" },
        {emailType:"MPending", keyword: "SAPCODENO", description :"" },
        {emailType:"MPending", keyword: "STATUS", description :"" },
        {emailType:"MPending", keyword: "SUBJECT", description :"" },
        {emailType:"MRejected", keyword: "DESC", description :"" },
        {emailType:"MRejected", keyword: "REQUESTEDON", description :"" },
        {emailType:"MRejected", keyword: "REQUESTNO", description :"" },
        {emailType:"MRejected", keyword: "SAPCODENO", description :"" },
        {emailType:"MRejected", keyword: "STATUS", description :"" },
        {emailType:"MRejected", keyword: "SUBJECT", description :"" },
        {emailType:"MCreated", keyword: "DESC", description :"" },
        {emailType:"MCreated", keyword: "REQUESTEDON", description :"" },
        {emailType:"MCreated", keyword: "REQUESTNO", description :"" },
        {emailType:"MCreated", keyword: "SAPCODENO", description :"" },
        {emailType:"MCreated", keyword: "STATUS", description :"" },
        {emailType:"MCreated", keyword: "SUBJECT", description :"" },
        {emailType:"MInProcess", keyword: "DESC", description :"" },
        {emailType:"MInProcess", keyword: "REQUESTEDON", description :"" },
        {emailType:"MInProcess", keyword: "REQUESTNO", description :"" },
        {emailType:"MInProcess", keyword: "SAPCODENO", description :"" },
        {emailType:"MInProcess", keyword: "STATUS", description :"" },
        {emailType:"MInProcess", keyword: "SUBJECT", description :"" },
        {emailType:"Offer-Email", keyword: "ACCEPTANCE_URL", description :"" },
        {emailType:"Offer-Email", keyword: "DESIGNATION", description :"" },
        {emailType:"Offer-Email-OS", keyword: "ACCEPTANCE_URL", description :"" },
        {emailType:"Offer-Approval", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Offer-Approval", keyword: "DESIGNATION", description :"" },
        {emailType:"Offer-Approval", keyword: "LOCATION", description :"" },
        {emailType:"Offer-Approval", keyword: "OFFER_APPROVAL_SEND_URL", description :"" },
        {emailType:"Offer-Approval", keyword: "PAY_GROUP", description :"" },
        {emailType:"Offer-Rejected", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Offer-Rejected", keyword: "DESIGNATION", description :"" },
        {emailType:"Offer-Rejected", keyword: "LOCATION", description :"" },
        {emailType:"Offer-Rejected", keyword: "PAY_GROUP", description :"" },
        {emailType:"Offer-Rejected", keyword: "REASON", description :"" },
        {emailType:"Offer-Withdrawn", keyword: "DESIGNATION", description :"" },
        {emailType:"Offer-Withdrawn", keyword: "OFFER_DATE", description :"" },
        {emailType:"Workflow-Cancelled", keyword: "OBJECT_ID", description :"" },
        {emailType:"Workflow-Cancelled", keyword: "REASON", description :"" },
        {emailType:"Workflow-Cancelled", keyword: "WORKFLOW_TYPE", description :"" },
        {emailType:"Candidate-Entry-OS", keyword: "DETAILS_ENTRY_URL", description :"" },
        {emailType:"Candidate-Entry-OS", keyword: "JOINING_DATE", description :"" },
        {emailType:"Offer-Email-Others", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Offer-Email-Others", keyword: "CREATED_BY", description :"" },
        {emailType:"Offer-Email-Others", keyword: "DESIGNATION", description :"" },
        {emailType:"Offer-Email-Others", keyword: "EMAIL_ID", description :"" },
        {emailType:"Offer-Email-Others", keyword: "JOINING_DATE", description :"" },
        {emailType:"Offer-Email-Others", keyword: "LOCATION", description :"" },
        {emailType:"Offer-Email-Others", keyword: "MOBILE_NO", description :"" },
        {emailType:"Offer-Email-Others", keyword: "OFFER_DATE", description :"" },
        {emailType:"Offer-Email-Others", keyword: "OFFER_NO", description :"" },
        {emailType:"Offer-Email-Others", keyword: "PAY_GROUP", description :"" },
        {emailType:"Offer-Withdrawn-Others", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Offer-Withdrawn-Others", keyword: "CREATED_BY", description :"" },
        {emailType:"Offer-Withdrawn-Others", keyword: "DESIGNATION", description :"" },
        {emailType:"Offer-Withdrawn-Others", keyword: "EMAIL_ID", description :"" },
        {emailType:"Offer-Withdrawn-Others", keyword: "JOINING_DATE", description :"" },
        {emailType:"Offer-Withdrawn-Others", keyword: "LOCATION", description :"" },
        {emailType:"Offer-Withdrawn-Others", keyword: "MOBILE_NO", description :"" },
        {emailType:"Offer-Withdrawn-Others", keyword: "OFFER_DATE", description :"" },
        {emailType:"Offer-Withdrawn-Others", keyword: "OFFER_NO", description :"" },
        {emailType:"Offer-Withdrawn-Others", keyword: "PAY_GROUP", description :"" },
        {emailType:"Offer-Withdrawn-Others", keyword: "REASON", description :"" },
        {emailType:"Appointment-Verification", keyword: "APPOINTMENT_VERIFICATION_PENDING_URL", description :"" },
        {emailType:"Appointment-Verification", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Appointment-Verification", keyword: "DESIGNATION", description :"" },
        {emailType:"Appointment-Verification", keyword: "LOCATION", description :"" },
        {emailType:"Appointment-Verification", keyword: "PAY_GROUP", description :"" },
        {emailType:"Appointment-Verification", keyword: "PLANT", description :"" },
        {emailType:"Appointment-Verification-Failed", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Appointment-Verification-Failed", keyword: "DESIGNATION", description :"" },
        {emailType:"Appointment-Verification-Failed", keyword: "LOCATION", description :"" },
        {emailType:"Appointment-Verification-Failed", keyword: "PAY_GROUP", description :"" },
        {emailType:"Appointment-Verification-Failed", keyword: "PLANT", description :"" },
        {emailType:"Appointment-Verification-Failed", keyword: "REASON", description :"" },
        {emailType:"Workflow-Reminder", keyword: "OBJECT_ID", description :"" },
        {emailType:"Workflow-Reminder", keyword: "WORKFLOW_TYPE", description :"" },
        {emailType:"Appointment-Approval", keyword: "APPROVE_PENDING_APPOINTMENT", description :"" },
        {emailType:"Appointment-Approval", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Appointment-Approval", keyword: "DESIGNATION", description :"" },
        {emailType:"Appointment-Approval", keyword: "LOCATION", description :"" },
        {emailType:"Appointment-Approval", keyword: "PAY_GROUP", description :"" },
        {emailType:"Appointment-Approval", keyword: "PLANT", description :"" },
        {emailType:"Appointment-Rejected", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Appointment-Rejected", keyword: "DESIGNATION", description :"" },
        {emailType:"Appointment-Rejected", keyword: "LOCATION", description :"" },
        {emailType:"Appointment-Rejected", keyword: "PAY_GROUP", description :"" },
        {emailType:"Appointment-Rejected", keyword: "PLANT", description :"" },
        {emailType:"Appointment-Rejected", keyword: "REASON", description :"" },
        {emailType:"Appointment-Email", keyword: "ACCEPTANCE_URL", description :"" },
        {emailType:"Appointment-Email", keyword: "DESIGNATION", description :"" },
        {emailType:"Appointment-Email-Others", keyword: "DATE_OF_JOINING", description :"" },
        {emailType:"Appointment-Email-Others", keyword: "DESIGNATION", description :"" },
        {emailType:"Appointment-Email-Others", keyword: "EMAIL_ID", description :"" },
        {emailType:"Appointment-Email-Others", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Appointment-Email-Others", keyword: "EMPLOYEE_NO", description :"" },
        {emailType:"Appointment-Email-Others", keyword: "LOCATION", description :"" },
        {emailType:"Appointment-Email-Others", keyword: "MOBILE_NO", description :"" },
        {emailType:"Appointment-Email-Others", keyword: "STATE", description :"" },
        {emailType:"Candidate-Before-Offer", keyword: "DESIGNATION", description :"" },
        {emailType:"Candidate-Before-Offer", keyword: "DETAILS_ENTRY_URL", description :"" },
        {emailType:"Candidate-Entry-Others", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Candidate-Entry-Others", keyword: "CREATED_BY", description :"" },
        {emailType:"Candidate-Entry-Others", keyword: "DESIGNATION", description :"" },
        {emailType:"Candidate-Entry-Others", keyword: "EMAIL_ID", description :"" },
        {emailType:"Candidate-Entry-Others", keyword: "JOINING_DATE", description :"" },
        {emailType:"Candidate-Entry-Others", keyword: "LOCATION", description :"" },
        {emailType:"Candidate-Entry-Others", keyword: "MOBILE_NO", description :"" },
        {emailType:"Candidate-Entry-Others", keyword: "OFFER_DATE", description :"" },
        {emailType:"Candidate-Entry-Others", keyword: "OFFER_NO", description :"" },
        {emailType:"Candidate-Entry-Others", keyword: "PAY_GROUP", description :"" },
        {emailType:"Resignation-WithDraw", keyword: "DESIGNATION", description :"" },
        {emailType:"Resignation-WithDraw", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Resignation-WithDraw", keyword: "JOINING_DATE", description :"" },
        {emailType:"Resignation-WithDraw", keyword: "LAST_WORKING_DATE", description :"" },
        {emailType:"Resignation-WithDraw", keyword: "LOCATION", description :"" },
        {emailType:"Resignation-WithDraw", keyword: "PAYGROUP", description :"" },
        {emailType:"Resignation-WithDraw", keyword: "PLANT", description :"" },
        {emailType:"Resignation-WithDraw", keyword: "REASON", description :"" },
        {emailType:"Resignation-Rejected", keyword: "DESIGNATION", description :"" },
        {emailType:"Resignation-Rejected", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Resignation-Rejected", keyword: "JOINING_DATE", description :"" },
        {emailType:"Resignation-Rejected", keyword: "LAST_WORKING_DATE", description :"" },
        {emailType:"Resignation-Rejected", keyword: "LOCATION", description :"" },
        {emailType:"Resignation-Rejected", keyword: "PAYGROUP", description :"" },
        {emailType:"Resignation-Rejected", keyword: "PLANT", description :"" },
        {emailType:"Resignation-Rejected", keyword: "REASON", description :"" },
        {emailType:"Resignation-Rejected", keyword: "RESIGNATION_DATE", description :"" },
        {emailType:"Resignation-Rejected", keyword: "DESIGNATION", description :"" },
        {emailType:"Resignation-Rejected", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Resignation-Rejected", keyword: "JOINING_DATE", description :"" },
        {emailType:"Resignation-Rejected", keyword: "LAST_WORKING_DATE", description :"" },
        {emailType:"Resignation-Rejected", keyword: "LOCATION", description :"" },
        {emailType:"Resignation-Rejected", keyword: "PAYGROUP", description :"" },
        {emailType:"Resignation-Rejected", keyword: "PLANT", description :"" },
        {emailType:"Resignation-Rejected", keyword: "REASON", description :"" },
        {emailType:"Resignation-Rejected", keyword: "RESIGNATION_DATE", description :"" },
        {emailType:"Resignation-Submitted", keyword: "DESIGNATION", description :"" },
        {emailType:"Resignation-Submitted", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Resignation-Submitted", keyword: "JOINING_DATE", description :"" },
        {emailType:"Resignation-Submitted", keyword: "LAST_WORKING_DATE", description :"" },
        {emailType:"Resignation-Submitted", keyword: "LOCATION", description :"" },
        {emailType:"Resignation-Submitted", keyword: "PAYGROUP", description :"" },
        {emailType:"Resignation-Submitted", keyword: "PLANT", description :"" },
        {emailType:"Resignation-Submitted", keyword: "REASON", description :"" },
        {emailType:"Resignation-Submitted", keyword: "RESIGNATION_DATE", description :"" },
        {emailType:"Resignation-Approval", keyword: "DESIGNATION", description :"" },
        {emailType:"Resignation-Approval", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Resignation-Approval", keyword: "JOINING_DATE", description :"" },
        {emailType:"Resignation-Approval", keyword: "LAST_WORKING_DATE", description :"" },
        {emailType:"Resignation-Approval", keyword: "LOCATION", description :"" },
        {emailType:"Resignation-Approval", keyword: "PAYGROUP", description :"" },
        {emailType:"Resignation-Approval", keyword: "PLANT", description :"" },
        {emailType:"Resignation-Approval", keyword: "REASON", description :"" },
        {emailType:"Resignation-Approval", keyword: "RESIGNATION_APPROVE_URL", description :"" },
        {emailType:"Resignation-Approval", keyword: "RESIGNATION_DATE", description :"" },
        {emailType:"Termination-Rejection", keyword: "APPLICABLE_DATE", description :"" },
        {emailType:"Termination-Rejection", keyword: "DESIGNATION", description :"" },
        {emailType:"Termination-Rejection", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Termination-Rejection", keyword: "JOINING_DATE", description :"" },
        {emailType:"Termination-Rejection", keyword: "LOCATION", description :"" },
        {emailType:"Termination-Rejection", keyword: "PAYGROUP", description :"" },
        {emailType:"Termination-Rejection", keyword: "PLANT", description :"" },
        {emailType:"Termination-Rejection", keyword: "REASON", description :"" },
        {emailType:"Termination-Rejection", keyword: "TERMINATION_DATE", description :"" },
        {emailType:"Termination-Approval", keyword: "APPLICABLE_DATE", description :"" },
        {emailType:"Termination-Approval", keyword: "DESIGNATION", description :"" },
        {emailType:"Termination-Approval", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Termination-Approval", keyword: "JOINING_DATE", description :"" },
        {emailType:"Termination-Approval", keyword: "LOCATION", description :"" },
        {emailType:"Termination-Approval", keyword: "PAYGROUP", description :"" },
        {emailType:"Termination-Approval", keyword: "PLANT", description :"" },
        {emailType:"Termination-Approval", keyword: "REASON", description :"" },
        {emailType:"Termination-Approval", keyword: "TERMINATION_APPROVE_URL", description :"" },
        {emailType:"Termination-Approval", keyword: "TERMINATION_DATE", description :"" },
        {emailType:"Termination-Submitted", keyword: "APPLICABLE_DATE", description :"" },
        {emailType:"Termination-Submitted", keyword: "DESIGNATION", description :"" },
        {emailType:"Termination-Submitted", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Termination-Submitted", keyword: "JOINING_DATE", description :"" },
        {emailType:"Termination-Submitted", keyword: "LOCATION", description :"" },
        {emailType:"Termination-Submitted", keyword: "PAYGROUP", description :"" },
        {emailType:"Termination-Submitted", keyword: "PLANT", description :"" },
        {emailType:"Termination-Submitted", keyword: "REASON", description :"" },
        {emailType:"Termination-Submitted", keyword: "TERMINATION_DATE", description :"" },
        {emailType:"Retirement-Extension-Rejection", keyword: "DESIGNATION", description :"" },
        {emailType:"Retirement-Extension-Rejection", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Retirement-Extension-Rejection", keyword: "EXTENSION_END", description :"" },
        {emailType:"Retirement-Extension-Rejection", keyword: "EXTENSION_START", description :"" },
        {emailType:"Retirement-Extension-Rejection", keyword: "LOCATION", description :"" },
        {emailType:"Retirement-Extension-Rejection", keyword: "PAYGROUP", description :"" },
        {emailType:"Retirement-Extension-Rejection", keyword: "PLANT", description :"" },
        {emailType:"Retirement-Extension-Rejection", keyword: "REASON", description :"" },
        {emailType:"Retirement-Extension-Rejection", keyword: "REMARKS", description :"" },
        {emailType:"Retirement-Extension-Rejection", keyword: "SUBMITTED_DATE", description :"" },
        {emailType:"Retirement-Extension-Approval", keyword: "DESIGNATION", description :"" },
        {emailType:"Retirement-Extension-Approval", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Retirement-Extension-Approval", keyword: "EXTENSION_END", description :"" },
        {emailType:"Retirement-Extension-Approval", keyword: "EXTENSION_START", description :"" },
        {emailType:"Retirement-Extension-Approval", keyword: "LOCATION", description :"" },
        {emailType:"Retirement-Extension-Approval", keyword: "PAYGROUP", description :"" },
        {emailType:"Retirement-Extension-Approval", keyword: "PLANT", description :"" },
        {emailType:"Retirement-Extension-Approval", keyword: "REMARKS", description :"" },
        {emailType:"Retirement-Extension-Approval", keyword: "RETIREMENT_EXTENSION_APPROVE_URL", description :"" },
        {emailType:"Retirement-Extension-Approval", keyword: "SUBMITTED_DATE", description :"" },
        {emailType:"Retirement-Extension-Submitted", keyword: "DESIGNATION", description :"" },
        {emailType:"Retirement-Extension-Submitted", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Retirement-Extension-Submitted", keyword: "EXTENSION_END", description :"" },
        {emailType:"Retirement-Extension-Submitted", keyword: "EXTENSION_START", description :"" },
        {emailType:"Retirement-Extension-Submitted", keyword: "LOCATION", description :"" },
        {emailType:"Retirement-Extension-Submitted", keyword: "PAYGROUP", description :"" },
        {emailType:"Retirement-Extension-Submitted", keyword: "PLANT", description :"" },
        {emailType:"Retirement-Extension-Submitted", keyword: "REMARKS", description :"" },
        {emailType:"Retirement-Extension-Submitted", keyword: "SUBMITTED_DATE", description :"" },
        {emailType:"Recall-Approval", keyword: "DESIGNATION", description :"" },
        {emailType:"Recall-Approval", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Recall-Approval", keyword: "LOCATION", description :"" },
        {emailType:"Recall-Approval", keyword: "PAYGROUP", description :"" },
        {emailType:"Recall-Approval", keyword: "PLANT", description :"" },
        {emailType:"Recall-Approval", keyword: "REASON", description :"" },
        {emailType:"Recall-Approval", keyword: "RECALL_APPROVE_URL", description :"" },
        {emailType:"Recall-Approval", keyword: "RECALL_DATE", description :"" },
        {emailType:"Recall-Rejection", keyword: "DESIGNATION", description :"" },
        {emailType:"Recall-Rejection", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Recall-Rejection", keyword: "LOCATION", description :"" },
        {emailType:"Recall-Rejection", keyword: "PAYGROUP", description :"" },
        {emailType:"Recall-Rejection", keyword: "PLANT", description :"" },
        {emailType:"Recall-Rejection", keyword: "REASON", description :"" },
        {emailType:"Recall-Rejection", keyword: "RECALL_DATE", description :"" },
        {emailType:"Recall-Submitted", keyword: "DESIGNATION", description :"" },
        {emailType:"Recall-Submitted", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Recall-Submitted", keyword: "LOCATION", description :"" },
        {emailType:"Recall-Submitted", keyword: "PAYGROUP", description :"" },
        {emailType:"Recall-Submitted", keyword: "PLANT", description :"" },
        {emailType:"Recall-Submitted", keyword: "REASON", description :"" },
        {emailType:"Recall-Submitted", keyword: "RECALL_DATE", description :"" },
        {emailType:"Offer-Exception-Approval", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Offer-Exception-Approval", keyword: "DESIGNATION", description :"" },
        {emailType:"Offer-Exception-Approval", keyword: "LOCATION", description :"" },
        {emailType:"Offer-Exception-Approval", keyword: "OFFER_APPROVAL_SEND_URL", description :"" },
        {emailType:"Offer-Exception-Approval", keyword: "PAY_GROUP", description :"" },
        {emailType:"Offer-Exception-Rejected", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Offer-Exception-Rejected", keyword: "DESIGNATION", description :"" },
        {emailType:"Offer-Exception-Rejected", keyword: "LOCATION", description :"" },
        {emailType:"Offer-Exception-Rejected", keyword: "PAY_GROUP", description :"" },
        {emailType:"Offer-Exception-Rejected", keyword: "REASON", description :"" },
        {emailType:"Confirmation-Approval", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Confirmation-Approval", keyword: "CONFIRMATION_APPROVE_URL", description :"" },
        {emailType:"Confirmation-Approval", keyword: "DESIGNATION", description :"" },
        {emailType:"Confirmation-Approval", keyword: "LOCATION", description :"" },
        {emailType:"Confirmation-Approval", keyword: "PAY_GROUP", description :"" },
        {emailType:"Confirmation-Approval", keyword: "PLANT", description :"" },
        {emailType:"Confirmation-Rejected", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Confirmation-Rejected", keyword: "DESIGNATION", description :"" },
        {emailType:"Confirmation-Rejected", keyword: "LOCATION", description :"" },
        {emailType:"Confirmation-Rejected", keyword: "PAY_GROUP", description :"" },
        {emailType:"Confirmation-Rejected", keyword: "PLANT", description :"" },
        {emailType:"Confirmation-Letter-Email", keyword: "LETTER_TYPE", description :"" },
        {emailType:"Experience-Email", keyword: "LETTER_TYPE", description :"" },
        {emailType:"FNF-Approval", keyword: "DESIGNATION", description :"" },
        {emailType:"FNF-Approval", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"FNF-Approval", keyword: "FNF_APPROVE_URL", description :"" },
        {emailType:"FNF-Approval", keyword: "LOCATION", description :"" },
        {emailType:"FNF-Approval", keyword: "PAYGROUP", description :"" },
        {emailType:"FNF-Approval", keyword: "PLANT", description :"" },
        {emailType:"FNF-Rejection", keyword: "DESIGNATION", description :"" },
        {emailType:"FNF-Rejection", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"FNF-Rejection", keyword: "LOCATION", description :"" },
        {emailType:"FNF-Rejection", keyword: "PAYGROUP", description :"" },
        {emailType:"FNF-Rejection", keyword: "PLANT", description :"" },
        {emailType:"FNF-Submitted", keyword: "DESIGNATION", description :"" },
        {emailType:"FNF-Submitted", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"FNF-Submitted", keyword: "LOCATION", description :"" },
        {emailType:"FNF-Submitted", keyword: "PAYGROUP", description :"" },
        {emailType:"FNF-Submitted", keyword: "PLANT", description :"" },
        {emailType:"Exit-Interview-Link", keyword: "DETAILS_ENTRY_URL", description :"" },
        {emailType:"Transfer-Rejection", keyword: "ADDITIONAL_NOTE", description :"" },
        {emailType:"Transfer-Rejection", keyword: "DESIGNATION", description :"" },
        {emailType:"Transfer-Rejection", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Transfer-Rejection", keyword: "JOINING_DATE", description :"" },
        {emailType:"Transfer-Rejection", keyword: "LOCATION", description :"" },
        {emailType:"Transfer-Rejection", keyword: "PAYGROUP", description :"" },
        {emailType:"Transfer-Rejection", keyword: "PLANT", description :"" },
        {emailType:"Transfer-Rejection", keyword: "TRANSFER_DATE", description :"" },
        {emailType:"Transfer-Approval", keyword: "ADDITIONAL_NOTE", description :"" },
        {emailType:"Transfer-Approval", keyword: "DESIGNATION", description :"" },
        {emailType:"Transfer-Approval", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Transfer-Approval", keyword: "JOINING_DATE", description :"" },
        {emailType:"Transfer-Approval", keyword: "LOCATION", description :"" },
        {emailType:"Transfer-Approval", keyword: "PAYGROUP", description :"" },
        {emailType:"Transfer-Approval", keyword: "PLANT", description :"" },
        {emailType:"Transfer-Approval", keyword: "TRANSFER_DATE", description :"" },
        {emailType:"Transfer-Submitted", keyword: "ADDITIONAL_NOTE", description :"" },
        {emailType:"Transfer-Submitted", keyword: "DESIGNATION", description :"" },
        {emailType:"Transfer-Submitted", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Transfer-Submitted", keyword: "JOINING_DATE", description :"" },
        {emailType:"Transfer-Submitted", keyword: "LOCATION", description :"" },
        {emailType:"Transfer-Submitted", keyword: "PAYGROUP", description :"" },
        {emailType:"Transfer-Submitted", keyword: "PLANT", description :"" },
        {emailType:"Transfer-Submitted", keyword: "TRANSFER_DATE", description :"" },
        {emailType:"Transfer-Submitted", keyword: "TRANSFER_SUBMITTED_URL", description :"" },
        {emailType:"Resignation-Rejection", keyword: "DESIGNATION", description :"" },
        {emailType:"Resignation-Rejection", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Resignation-Rejection", keyword: "JOINING_DATE", description :"" },
        {emailType:"Resignation-Rejection", keyword: "LAST_WORKING_DATE", description :"" },
        {emailType:"Resignation-Rejection", keyword: "LOCATION", description :"" },
        {emailType:"Resignation-Rejection", keyword: "PAYGROUP", description :"" },
        {emailType:"Resignation-Rejection", keyword: "PLANT", description :"" },
        {emailType:"Resignation-Rejection", keyword: "Reason", description :"" },
        {emailType:"Resignation-Rejection", keyword: "RESIGNATION_DATE", description :"" },
        {emailType:"Interviewer-Notification", keyword: "ADDITIONAL_NOTES", description :"" },
        {emailType:"Interviewer-Notification", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Interviewer-Notification", keyword: "INTERVIEW_DATE", description :"" },
        {emailType:"Interviewer-Notification", keyword: "INTERVIEW_END_TIME", description :"" },
        {emailType:"Interviewer-Notification", keyword: "INTERVIEW_MODE", description :"" },
        {emailType:"Interviewer-Notification", keyword: "INTERVIEW_ROUND", description :"" },
        {emailType:"Interviewer-Notification", keyword: "INTERVIEW_START_TIME", description :"" },
        {emailType:"Interviewer-Notification", keyword: "INTERVIEWERS", description :"" },
        {emailType:"Interviewer-Notification", keyword: "JOB_TITLE", description :"" },
        {emailType:"Interviewer-Notification", keyword: "REQUISITION_ID", description :"" },
        {emailType:"Send-Email-Notification", keyword: "EMAIL_BODY", description :"" },
        {emailType:"Delegation-Created-Email", keyword: "DELEGATION_FROM", description :"" },
        {emailType:"Delegation-Created-Email", keyword: "FROM_DATE", description :"" },
        {emailType:"Delegation-Created-Email", keyword: "TO_DATE", description :"" },
        {emailType:"Delegation-Updated-Email", keyword: "DELEGATION_FROM", description :"" },
        {emailType:"Delegation-Updated-Email", keyword: "FROM_DATE", description :"" },
        {emailType:"Delegation-Updated-Email", keyword: "TO_DATE", description :"" },
        {emailType:"Delegation-Deleted-Email", keyword: "DELEGATION_FROM", description :"" },
        {emailType:"Delegation-Deleted-Email", keyword: "FROM_DATE", description :"" },
        {emailType:"Delegation-Deleted-Email", keyword: "TO_DATE", description :"" },
        {emailType:"Update-Profile-Approval", keyword: "APPROVAL_URL", description :"" },
        {emailType:"Update-Profile-Approval", keyword: "DESIGNATION", description :"" },
        {emailType:"Update-Profile-Approval", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Update-Profile-Approval", keyword: "LOCATION", description :"" },
        {emailType:"Update-Profile-Approval", keyword: "PAYGROUP", description :"" },
        {emailType:"Update-Profile-Approval", keyword: "PLANT", description :"" },
        {emailType:"Update-Profile-Approval", keyword: "REASON", description :"" },
        {emailType:"Update-Profile-Submitted", keyword: "DESIGNATION", description :"" },
        {emailType:"Update-Profile-Submitted", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Update-Profile-Submitted", keyword: "LOCATION", description :"" },
        {emailType:"Update-Profile-Submitted", keyword: "PAYGROUP", description :"" },
        {emailType:"Update-Profile-Submitted", keyword: "PLANT", description :"" },
        {emailType:"Update-Profile-Submitted", keyword: "REASON", description :"" },
        {emailType:"Update-Profile-Rejection", keyword: "DESIGNATION", description :"" },
        {emailType:"Update-Profile-Rejection", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Update-Profile-Rejection", keyword: "LOCATION", description :"" },
        {emailType:"Update-Profile-Rejection", keyword: "PAYGROUP", description :"" },
        {emailType:"Update-Profile-Rejection", keyword: "PLANT", description :"" },
        {emailType:"Update-Profile-Rejection", keyword: "REASON", description :"" },
        {emailType:"Appraisal-Rejected", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Appraisal-Rejected", keyword: "DESIGNATION", description :"" },
        {emailType:"Appraisal-Rejected", keyword: "LOCATION", description :"" },
        {emailType:"Appraisal-Rejected", keyword: "PAY_GROUP", description :"" },
        {emailType:"Appraisal-Rejected", keyword: "PLANT", description :"" },
        {emailType:"Appraisal-Rejected", keyword: "REASON", description :"" },
        {emailType:"Appraisal-Initiated", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Appraisal-Initiated", keyword: "DESIGNATION", description :"" },
        {emailType:"Appraisal-Initiated", keyword: "LOCATION", description :"" },
        {emailType:"Appraisal-Initiated", keyword: "PAY_GROUP", description :"" },
        {emailType:"Appraisal-Initiated", keyword: "PLANT", description :"" },
        {emailType:"Appraisal-Approval", keyword: "APPRAISAL-APPROVAL_URL", description :"" },
        {emailType:"Appraisal-Approval", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Appraisal-Approval", keyword: "DESIGNATION", description :"" },
        {emailType:"Appraisal-Approval", keyword: "LOCATION", description :"" },
        {emailType:"Appraisal-Approval", keyword: "PAY_GROUP", description :"" },
        {emailType:"Appraisal-Approval", keyword: "PLANT", description :"" },
        {emailType:"Appraisal-Letter-Email", keyword: "EFFECTIVE_DATE", description :"" },
        {emailType:"Appraisal-Recommendation", keyword: "APPRAISAL-APPROVAL_URL", description :"" },
        {emailType:"Appraisal-Recommendation", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Appraisal-Recommendation", keyword: "DESIGNATION", description :"" },
        {emailType:"Appraisal-Recommendation", keyword: "LOCATION", description :"" },
        {emailType:"Appraisal-Recommendation", keyword: "PAY_GROUP", description :"" },
        {emailType:"Appraisal-Recommendation", keyword: "PERIOD", description :"" },
        {emailType:"Appraisal-Recommendation", keyword: "PLANT", description :"" },
        {emailType:"Resignation-Checklist-Email", keyword: "ASSIGNED_TO", description :"" },
        {emailType:"Resignation-Checklist-Email", keyword: "CHECKLIST_DETAIL", description :"" },
        {emailType:"Resignation-Checklist-Email", keyword: "CHECKLIST_TYPE", description :"" },
        {emailType:"Resignation-Checklist-Email", keyword: "DESIGNATION", description :"" },
        {emailType:"Resignation-Checklist-Email", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Resignation-Checklist-Email", keyword: "EMPLOYEE_NO", description :"" },
        {emailType:"Resignation-Checklist-Email", keyword: "LOCATION", description :"" },
        {emailType:"Resignation-Checklist-Email", keyword: "PAYGROUP", description :"" },
        {emailType:"Resignation-Checklist-Email", keyword: "PLANT", description :"" },
        {emailType:"Resignation-Checklist-Email", keyword: "RELIEVING_DATE", description :"" },
        {emailType:"Resignation-Checklist-Email", keyword: "STATUS", description :"" },
        {emailType:"Termination-Checklist-Email", keyword: "ASSIGNED_TO", description :"" },
        {emailType:"Termination-Checklist-Email", keyword: "CHECKLIST_DETAIL", description :"" },
        {emailType:"Termination-Checklist-Email", keyword: "CHECKLIST_TYPE", description :"" },
        {emailType:"Termination-Checklist-Email", keyword: "DESIGNATION", description :"" },
        {emailType:"Termination-Checklist-Email", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Termination-Checklist-Email", keyword: "EMPLOYEE_NO", description :"" },
        {emailType:"Termination-Checklist-Email", keyword: "LOCATION", description :"" },
        {emailType:"Termination-Checklist-Email", keyword: "PAYGROUP", description :"" },
        {emailType:"Termination-Checklist-Email", keyword: "PLANT", description :"" },
        {emailType:"Termination-Checklist-Email", keyword: "RELIEVING_DATE", description :"" },
        {emailType:"Termination-Checklist-Email", keyword: "STATUS", description :"" },
        {emailType:"Onboarding-Checklist-Email", keyword: "ASSIGNED_TO", description :"" },
        {emailType:"Onboarding-Checklist-Email", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Onboarding-Checklist-Email", keyword: "CHECKLIST_DETAIL", description :"" },
        {emailType:"Onboarding-Checklist-Email", keyword: "CHECKLIST_TYPE", description :"" },
        {emailType:"Onboarding-Checklist-Email", keyword: "DESIGNATION", description :"" },
        {emailType:"Onboarding-Checklist-Email", keyword: "JOINING_DATE", description :"" },
        {emailType:"Onboarding-Checklist-Email", keyword: "LOCATION", description :"" },
        {emailType:"Onboarding-Checklist-Email", keyword: "OFFER_ID", description :"" },
        {emailType:"Onboarding-Checklist-Email", keyword: "PAYGROUP", description :"" },
        {emailType:"Onboarding-Checklist-Email", keyword: "PLANT", description :"" },
        {emailType:"Onboarding-Checklist-Email", keyword: "STATUS", description :"" },
        {emailType:"Resignation-Approved", keyword: "DESIGNATION", description :"" },
        {emailType:"Resignation-Approved", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Resignation-Approved", keyword: "JOINING_DATE", description :"" },
        {emailType:"Resignation-Approved", keyword: "LAST_WORKING_DATE", description :"" },
        {emailType:"Resignation-Approved", keyword: "LOCATION", description :"" },
        {emailType:"Resignation-Approved", keyword: "PAYGROUP", description :"" },
        {emailType:"Resignation-Approved", keyword: "PLANT", description :"" },
        {emailType:"Resignation-Approved", keyword: "REASON", description :"" },
        {emailType:"Resignation-Approved", keyword: "RESIGNATION_DATE", description :"" },
        {emailType:"Resignation-ExitInitiated", keyword: "DESIGNATION", description :"" },
        {emailType:"Resignation-ExitInitiated", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Resignation-ExitInitiated", keyword: "JOINING_DATE", description :"" },
        {emailType:"Resignation-ExitInitiated", keyword: "LAST_WORKING_DATE", description :"" },
        {emailType:"Resignation-ExitInitiated", keyword: "LOCATION", description :"" },
        {emailType:"Resignation-ExitInitiated", keyword: "PAYGROUP", description :"" },
        {emailType:"Resignation-ExitInitiated", keyword: "PLANT", description :"" },
        {emailType:"Resignation-ExitInitiated", keyword: "REASON", description :"" },
        {emailType:"Resignation-ExitInitiated", keyword: "RESIGNATION_DATE", description :"" },
        {emailType:"Resignation-ExitCompleted", keyword: "DESIGNATION", description :"" },
        {emailType:"Resignation-ExitCompleted", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Resignation-ExitCompleted", keyword: "JOINING_DATE", description :"" },
        {emailType:"Resignation-ExitCompleted", keyword: "LAST_WORKING_DATE", description :"" },
        {emailType:"Resignation-ExitCompleted", keyword: "LOCATION", description :"" },
        {emailType:"Resignation-ExitCompleted", keyword: "PAYGROUP", description :"" },
        {emailType:"Resignation-ExitCompleted", keyword: "PLANT", description :"" },
        {emailType:"Resignation-ExitCompleted", keyword: "REASON", description :"" },
        {emailType:"Resignation-ExitCompleted", keyword: "RESIGNATION_DATE", description :"" },
        {emailType:"Termination-Submitted", keyword: "APPLICABLE_DATE", description :"" },
        {emailType:"Termination-Submitted", keyword: "DESIGNATION", description :"" },
        {emailType:"Termination-Submitted", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Termination-Submitted", keyword: "JOINING_DATE", description :"" },
        {emailType:"Termination-Submitted", keyword: "LOCATION", description :"" },
        {emailType:"Termination-Submitted", keyword: "PAYGROUP", description :"" },
        {emailType:"Termination-Submitted", keyword: "PLANT", description :"" },
        {emailType:"Termination-Submitted", keyword: "REASON", description :"" },
        {emailType:"Termination-Submitted", keyword: "TERMINATION_DATE", description :"" },
        {emailType:"Transfer-Approved", keyword: "ADDITIONAL_NOTE", description :"" },
        {emailType:"Transfer-Approved", keyword: "DESIGNATION", description :"" },
        {emailType:"Transfer-Approved", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Transfer-Approved", keyword: "JOINING_DATE", description :"" },
        {emailType:"Transfer-Approved", keyword: "LOCATION", description :"" },
        {emailType:"Transfer-Approved", keyword: "PAYGROUP", description :"" },
        {emailType:"Transfer-Approved", keyword: "PLANT", description :"" },
        {emailType:"Transfer-Approved", keyword: "TRANSFER_DATE", description :"" },
        {emailType:"Recall-Approved", keyword: "DESIGNATION", description :"" },
        {emailType:"Recall-Approved", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Recall-Approved", keyword: "LOCATION", description :"" },
        {emailType:"Recall-Approved", keyword: "PAYGROUP", description :"" },
        {emailType:"Recall-Approved", keyword: "PLANT", description :"" },
        {emailType:"Recall-Approved", keyword: "REASON", description :"" },
        {emailType:"Recall-Approved", keyword: "RECALL_DATE", description :"" },
        {emailType:"Retirement-Extension-Approved", keyword: "DESIGNATION", description :"" },
        {emailType:"Retirement-Extension-Approved", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Retirement-Extension-Approved", keyword: "EXTENSION_END", description :"" },
        {emailType:"Retirement-Extension-Approved", keyword: "EXTENSION_START", description :"" },
        {emailType:"Retirement-Extension-Approved", keyword: "LOCATION", description :"" },
        {emailType:"Retirement-Extension-Approved", keyword: "PAYGROUP", description :"" },
        {emailType:"Retirement-Extension-Approved", keyword: "PLANT", description :"" },
        {emailType:"Retirement-Extension-Approved", keyword: "REMARKS", description :"" },
        {emailType:"Retirement-Extension-Approved", keyword: "SUBMITTED_DATE", description :"" },
        {emailType:"Termination-Approved", keyword: "APPLICABLE_DATE", description :"" },
        {emailType:"Termination-Approved", keyword: "DESIGNATION", description :"" },
        {emailType:"Termination-Approved", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Termination-Approved", keyword: "JOINING_DATE", description :"" },
        {emailType:"Termination-Approved", keyword: "LOCATION", description :"" },
        {emailType:"Termination-Approved", keyword: "PAYGROUP", description :"" },
        {emailType:"Termination-Approved", keyword: "PLANT", description :"" },
        {emailType:"Termination-Approved", keyword: "REASON", description :"" },
        {emailType:"Termination-Approved", keyword: "TERMINATION_DATE", description :"" },
        {emailType:"Resignation-Exited", keyword: "DESIGNATION", description :"" },
        {emailType:"Resignation-Exited", keyword: "EMPLOYEE_NAME", description :"" },
        {emailType:"Resignation-Exited", keyword: "JOINING_DATE", description :"" },
        {emailType:"Resignation-Exited", keyword: "LAST_WORKING_DATE", description :"" },
        {emailType:"Resignation-Exited", keyword: "LOCATION", description :"" },
        {emailType:"Resignation-Exited", keyword: "PAYGROUP", description :"" },
        {emailType:"Resignation-Exited", keyword: "PLANT", description :"" },
        {emailType:"Resignation-Exited", keyword: "REASON", description :"" },
        {emailType:"Resignation-Exited", keyword: "RESIGNATION_DATE", description :"" },
        {emailType:"Appraisal-Approved", keyword: "APPRAISALTYPE", description :"" },
        {emailType:"Appraisal-Approved", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Appraisal-Approved", keyword: "DESIGNATION", description :"" },
        {emailType:"Appraisal-Approved", keyword: "EFFECTIVEDATEMONTH", description :"" },
        {emailType:"Appraisal-Approved", keyword: "EFFECTIVEDATEyear", description :"" },
        {emailType:"Appraisal-Approved", keyword: "LOCATION", description :"" },
        {emailType:"Appraisal-Approved", keyword: "PAY_GROUP", description :"" },
        {emailType:"Appraisal-Approved", keyword: "PLANT", description :"" },
        {emailType:"Appraisal-Approved", keyword: "RATING", description :"" },
        {emailType:"Appraisal-Submitted", keyword: "APPRAISALTYPE", description :"" },
        {emailType:"Appraisal-Submitted", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Appraisal-Submitted", keyword: "DESIGNATION", description :"" },
        {emailType:"Appraisal-Submitted", keyword: "EFFECTIVEDATEMONTH", description :"" },
        {emailType:"Appraisal-Submitted", keyword: "EFFECTIVEDATEyear", description :"" },
        {emailType:"Appraisal-Submitted", keyword: "LOCATION", description :"" },
        {emailType:"Appraisal-Submitted", keyword: "PAY_GROUP", description :"" },
        {emailType:"Appraisal-Submitted", keyword: "PLANT", description :"" },
        {emailType:"Appraisal-Submitted", keyword: "RATING", description :"" },
        {emailType:"Confirmation-Submitted", keyword: "ADDTIONALNOTES", description :"" },
        {emailType:"Confirmation-Submitted", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Confirmation-Submitted", keyword: "CONFIRMATIONTYPE", description :"" },
        {emailType:"Confirmation-Submitted", keyword: "DESIGNATION", description :"" },
        {emailType:"Confirmation-Submitted", keyword: "EFFECTIVEDATEMONTH", description :"" },
        {emailType:"Confirmation-Submitted", keyword: "EFFECTIVEDATEyear", description :"" },
        {emailType:"Confirmation-Submitted", keyword: "EXTENSIONREASON", description :"" },
        {emailType:"Confirmation-Submitted", keyword: "LOCATION", description :"" },
        {emailType:"Confirmation-Submitted", keyword: "PAY_GROUP", description :"" },
        {emailType:"Confirmation-Submitted", keyword: "PLANT", description :"" },
        {emailType:"Confirmation-Submitted", keyword: "RATING", description :"" },
        {emailType:"Confirmation-Approved", keyword: "ADDTIONALNOTES", description :"" },
        {emailType:"Confirmation-Approved", keyword: "CANDIDATE_NAME", description :"" },
        {emailType:"Confirmation-Approved", keyword: "CONFIRMATIONTYPE", description :"" },
        {emailType:"Confirmation-Approved", keyword: "DESIGNATION", description :"" },
        {emailType:"Confirmation-Approved", keyword: "EFFECTIVEDATEMONTH", description :"" },
        {emailType:"Confirmation-Approved", keyword: "EFFECTIVEDATEyear", description :"" },
        {emailType:"Confirmation-Approved", keyword: "EXTENSIONREASON", description :"" },
        {emailType:"Confirmation-Approved", keyword: "LOCATION", description :"" },
        {emailType:"Confirmation-Approved", keyword: "PAY_GROUP", description :"" },
        {emailType:"Confirmation-Approved", keyword: "PLANT", description :"" },
        {emailType:"Confirmation-Approved", keyword: "RATING", description :"" },
        {emailType:"Confirmation-Due-Email", keyword: "EMPLOYEE_TABLE", description :"" },
        {emailType:"Task-Approved", keyword: "APPROVER_ROLE", description :"" },
        {emailType:"Task-Approved", keyword: "OBJECT_ID", description :"" },
        {emailType:"Task-Approved", keyword: "WORKFLOW_TYPE", description :"" },
        {emailType:"Resignation-WithDraw", keyword: "RESIGNATION_DATE", description :"" },        
            ];

  constructor(private httpService: HttpService,
    private router: Router,private util: Util) {
      currentUser: AuthData;
     }

  ngOnInit() {
    this.currentUser = JSON.parse(localStorage.getItem('currentUser'));
    this.filterModel.pageSize = 10;
    this.getEmailTemplateList();
  }

  gotoPage(no){
    if( this.filterModel.pageNo == no) return;
    this.filterModel.pageNo = no;
    this.getData();    
  }

  pageSizeChange(){
    this.filterModel.pageNo = 1;    
    this.getData();    
  }
  

  getEmailTemplateList() {
    this.filterModel.pageNo = 1;
    this.getData();
  
  }

  getData(){
    this.isLoading = true;    
    this.httpService.HRpost(APIURLS.EMAIL_TEMPLATE_LIST, this.filterModel).then((data: any) => {
      this.filterData = data;
     console.log(this.filterData.list);
     for(var item of this.filterData.list){
      item.statusColor = this.statusList.find(x=>x.type == item.active).color;      
    }
      this.isLoading = false;
    }).catch(error => {
      this.isLoading = false;      
    }); 
  }

  EditLine(item, index){    
    this.item = Object.assign({}, item);
    this.editIndex = index;
    this.keywordsList = this.keywordsFullList.filter(x=>this.item.actionType.includes(x.emailType));
    $("#detailsModal").modal("show");
  }

  update()
  {
    toastr.info("Updating...");
    this.isLoading = true;

    this.item.modifiedBy = this.currentUser.uid;
    this.item.modifiedDate = this.util.getFormatedDateTime(new Date());

    this.httpService.HRpost(APIURLS.EMAIL_TEMPLATE_UPDATE, this.item)
      .then((data: any) => {
        if (data == 200 || data.success) {
          toastr.success("Successfully updated the details.");
          $("#detailsModal").modal("hide");
          this.getData();
        }
        this.isLoading = false;
      }).catch(error => {
        this.isLoading = false;
        toastr.error('Error updating details...' + error);
      })
  }
  
  RenderMail(item){    
    this.item = Object.assign({}, item);
    $("#renderModal").modal("show");
  }


  print(): void {
 
      let printContents, popupWin, footerContent;
      printContents = document.getElementById('printable');
      //footerContent = document.getElementById('print-footer').innerHTML;
      
      const htmlContent = printContents.innerHTML;

      const blob = new Blob ([htmlContent],{ type :'text/HTML'});
      const url = window.URL.createObjectURL(blob);

      const a=document.createElement("a");
      a.href = url;
      a.download ="email-template.html";
      a.click();
      window.URL.revokeObjectURL(url);


    }

    exportList: any = {};
    exportData()
    {
      this.isLoading = true;    
      this.filterModel.export = true;
      this.httpService.HRpost(APIURLS.EMAIL_TEMPLATE_LIST, this.filterModel).then((data: any) => {
        this.exportList = data;
        this.filterModel.export = false;
      //$("#renderModalAll").modal("show");
      setTimeout(() => {
        this.printmultiple();
      }, 100); 
        this.isLoading = false;
      }).catch(error => {
        this.filterModel.export = false;
        this.isLoading = false;      
      }); 
      
    }

    printmultiple(): void {
 
      let printContents, popupWin, footerContent;
      printContents = document.getElementById('printableall');
      //footerContent = document.getElementById('print-footer').innerHTML;
      
      const htmlContent = printContents.innerHTML;

      const blob = new Blob ([htmlContent],{ type :'text/HTML'});
      const url = window.URL.createObjectURL(blob);

      const a=document.createElement("a");
      a.href = url;
      a.download ="email-templates.html";
      a.click();
      window.URL.revokeObjectURL(url);
    }
     
    show :any ="Hide";
    showPassword()
    {
      this.show = !this.show;

    }
}
