import { NPDCMD } from "./NPDCmddetails.model";
import { NPDCQA } from "./NPDCqadetails.model";
import { NPDDIST } from "./NPDDistdetails.model";
import { NPDHOD } from "./NPDHoddetails.model";
import { NPDIPR } from "./NPDIprdetails.model";
import { NPDMED } from "./NPDMeddetails.model";
import { NPDRND } from "./NPDRnddetails.model";
import { NPDSCM } from "./NPDScmdetails.model";
import { NPDSTRATEGIC } from "./NPDStrategicdetails.model";

export class NPDRequest {
    id: number;
    requestNo: string;
    requestedBy: string;
    requestDate: string;
    location: string;
    division: string;
    genericName: string;
    composition: string;
    dosageForm: string;
    dosageDetails: string;
    brandName: string;
    brandSearch: string;
    brandValue: string;
    strength: string;
    proposedPacking: string;
    packingConfig: string;
    salePack: string;
    saleunitPackSize: string;
    saleunitPerCarton: string;
    saleunitsPerShipper: string;
    physicianSample: string;
    physicianSampleQuantity: string;
    compititorSample: string;
    specificFormulationDevelopmentRequirement: string;
    launchReq: string;
    postLaunchReq: string;
    marketShare: string;
    salesForecastUnitsMonth1: string;
    salesForecastUnitsMonth2: string;
    salesForecastUnitsMonth3: string;
    salesForecastUnitsQtr2: string;
    salesForecastUnitsQtr3: string;
    salesForecastUnitsQtr4: string;
    salesForecastUnitsYear1: string;
    salesForecastUnitsYear2: string;
    salesForecastUnitsYear3: string;
    salesForecastValueYear1: string;
    salesForecastValueYear2: string;
    salesForecastValueYear3: string;
    marketInfoIndia: string;
    marketInfoGlobal: string;
    compititorBrand: string;
    growth: string;
    totalMarketDrug: string;
    compititorBrandsCount: string;
    proposedmicroPrice: string;
    expectedMarketShareYear1: string;
    expectedMarketShareYear2: string;
    expectedMarketShareYear3: string;
    justificationLaunch: string;
    additionalInformationIfRequired: string;
    originatorBrandSales: string;
    attachments: string;
    submitedDate: string;
    finalDocNo: string;
    finalDocDate: string;
    finalSerialNo: string;
    apprvrStatus: string;
    approveType: string;
    stage: string;
    npdHodInitialstageSubmitFlag: number;
    npdMedicalDeptDetailsSubmitFlag: number;
    npdIprDeptDetailsSubmitFlag: number;
    npdCqaDeptDetailsSubmitFlag: number;
    npdSupplychainDeptDetailsSubmitFlag: number;
    npdRndDeptDetailsSubmitFlag: number;
    npdStrategicDeptDetailsSubmitFlag: number;
    npdDistributionDeptDetailsSubmitFlag: number;
    npdOtherDeptDetailsSubmitFlag: number;
    npdHodFinalstageSubmitFlag: number;
    npdCmdDetailsSubmitFlag: number;


    employeeId:string;
    fullName:string;
    department:string;
    designation:string;
    isSelected:boolean;
    brandsList:any[]=[];
    pendingApprover:string;
    lastApprover:string;

    type:string;
    hod:string;
    comments:string;

    hodModel={} as NPDHOD;
    medModel={} as NPDMED;
    iprModel={} as NPDIPR;
    cqaModel={} as NPDCQA;
    supplyChainModel={} as NPDSCM;
    rndModel={} as NPDRND;
    strategicModel={} as NPDSTRATEGIC;
    distModel={} as NPDDIST;
    cmdModel={} as NPDCMD; 
}