export class DocDestruction {
    id!: number;
    location: string
    empCode: string
    fromDept: string
    reqStatus: string
    category: string
    initialDocNo: string
    initialDocDate: string
    finalDocNo: string
    finalDocDate: string
    lastApprover: string
    pendingApprover: string
    role: string
    docNo: string
    docType: string
    docShtDesc: string
    docDesc: string
    barcode: string
    docRoom: string
    docRack: string
    docBin: string
    approver: string
    borrowStatus: string
    docSubCategory: string
    personResponsible: string
    library!: number;
    productName: string
    batchNo: string
    boxDescription: string
    mfacDate: string
    agrregation: string
    arNo: string
    effectiveDate: string
    boxNo: string
    expiryDate: string
    agrregationComp: string
    rackRange: string
    prevDocRoom: string
    prevDocRack: string
    prevDocBin: string
    prevRackRange: string
    approvedDate: string
    rackFlag!: number;
    boxBarcode: string
    retentionPeriod: string
    assignApprover: string
    assignedApprover: string
    selectApprover: string
    selectedApprover: string
    substitutionFlag!: number;
    subPerson: string
    subFrom: string
    type: string
    message: string
    submittedDate: string
    destructionNo: string
    fullName: string
    designation: string
}