export class NewSalary{
    constructor(
        public id: number,
        public fkAssessmentId: number,
        public baseLocation: string,
        public basic: string,
        public bonus: string,
        public booksPeriodicals: string,
        public carFuel: string,
        public category: string,
        public createdBy: string,
        public createdDate: Date,
        public currentDesignation: string,
        public dept: string,
        public driveReim: string,
        public effectiveDate: string,
        public esiEmployer: string,
        public fixedAnnualCtc: string,
        
        public fkCalenderId: string,
        public fkEmpId: string,
        public fkEmployeeId: string,
        public gender: string,
        public grossMedicalClaim: string,
        public hra: string,
        
        public isActive: boolean,
        public lta: string,
        public meal: string,
        public modifiedBy: string,
        public modifiedDate: string,
        public monthlyGross: string,
        public offerLetterFormat: string,
        public pfEmployee: string,
        public pfEmployer: string,
        public remarks: string,
        public revisedDesignation: string,
        public softwareAllowance: string,
        public telephone: string,
        public temp3: string,
        public temp4: string,
        public temp5: string,
        public temp6: string,
        public temp7: string,
        public temp8: string,
        public temp9: string,
        public temp10: string,
        public temp11: string,
        public temp12: string,
        public temp13: string,
        public temp14: string,
        public temp15: string,
        public variablePay: string,
    ){}
}