import { Component, OnInit } from '@angular/core';
import { HttpService } from '../../../shared/http-service';
import { APIURLS } from '../../../shared/api-url';
import { Router, RouterModule } from '@angular/router';
import { ExcelService } from '../../../shared/excel-service';
import { AuthData } from '../../../auth/auth.model';
import { LetterTemplateFilter } from './letter-template-filter.model'
import { LetterTemplate } from './letter-template.model';
import { AngularEditorConfig } from '@kolkov/angular-editor';
import { Util } from '../../Services/util.service';

declare var $: any;
declare var toastr: any;

@Component({
  selector: 'app-letter-templates',
  templateUrl: './letter-templates.component.html',
  styleUrls: ['./letter-templates.component.css'],
  providers: [Util]
})
export class LetterTemplatesComponent implements OnInit {
  id: number = 0;
  action: string
  isLoading: boolean = false;
  filterData: any = {};
  currentUser!: AuthData;
  letterTemplateDetails= {} as LetterTemplate;
  filterModel: LetterTemplateFilter = {} as LetterTemplateFilter;
  letterTemplateList: any[] = [];
  selectedLetterTemplateType : any = null;
  selectedLetterTemplateName : any = null;  
  selectedCreatedBy : any = null;  
  item: any = {};
  editIndex : number = -1;
  editorConfig: AngularEditorConfig = {
    editable: true,
    spellcheck: true,
    height: 'auto',
    minHeight: '300px',
    maxHeight: 'auto',
    width: 'auto',
    enableToolbar: true,
    showToolbar: true,
    placeholder: 'Enter text here...',
    sanitize: true,
    toolbarPosition: 'top',
};
isEdit : boolean = false;
typeList = [
  { type: "Appointment Letter" , color:"info"},
  { type: "Appraisal Letter", color:"info" },    
  { type: "Appointment Letter", color:"info" },    
  { type: "Confirmation Letter", color:"info"},
  { type: "Experience Letter", color:"info" },    
  { type: "Offer Letter", color:"info" },  
  { type: "Recall", color:"info" }, 
  { type: "Relieving Letter", color:"info" }, 
  { type: "Resignation Accept", color:"info" }, 
  { type: "Resignation Letter", color:"info" }, 
  { type: "Retirement Extension", color:"info" }, 
  { type: "Service Withdrawn Experience Letter", color:"info" }, 
  { type: "Service Withdrawn Relieving Letter", color:"info" }, 
  { type: "Transfer Letter", color:"info" },   
];

keywordsList = [];

keywordsFullList = [
  {templateType:"Appointment Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Appointment Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_NO", description :"" },
{templateType:"Appointment Letter", keyword: "CITY", description :"" },
{templateType:"Appointment Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "HOUSE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "INITIAL", description :"" },
{templateType:"Appointment Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "NOTE", description :"" },
{templateType:"Appointment Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Appointment Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Appointment Letter", keyword: "PROBATION_MONTHS", description :"" },
{templateType:"Appointment Letter", keyword: "ROLE", description :"" },
{templateType:"Appointment Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appointment Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "TITLE", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Appointment Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_NO", description :"" },
{templateType:"Appointment Letter", keyword: "CITY", description :"" },
{templateType:"Appointment Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "HOUSE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "INITIAL", description :"" },
{templateType:"Appointment Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "NOTE", description :"" },
{templateType:"Appointment Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Appointment Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Appointment Letter", keyword: "PROBATION_MONTHS", description :"" },
{templateType:"Appointment Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appointment Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "TITLE", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Appointment Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_NO", description :"" },
{templateType:"Appointment Letter", keyword: "CITY", description :"" },
{templateType:"Appointment Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "HOUSE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "INITIAL", description :"" },
{templateType:"Appointment Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "NOTE", description :"" },
{templateType:"Appointment Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Appointment Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Appointment Letter", keyword: "PROBATION_MONTHS", description :"" },
{templateType:"Appointment Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appointment Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "TITLE", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Appointment Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_NO", description :"" },
{templateType:"Appointment Letter", keyword: "CITY", description :"" },
{templateType:"Appointment Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "HOUSE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "INITIAL", description :"" },
{templateType:"Appointment Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "NOTE", description :"" },
{templateType:"Appointment Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Appointment Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Appointment Letter", keyword: "PROBATION_MONTHS", description :"" },
{templateType:"Appointment Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appointment Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "TITLE", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Appointment Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_NO", description :"" },
{templateType:"Appointment Letter", keyword: "CITY", description :"" },
{templateType:"Appointment Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "HOUSE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "INITIAL", description :"" },
{templateType:"Appointment Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "NOTE", description :"" },
{templateType:"Appointment Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Appointment Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Appointment Letter", keyword: "PROBATION_MONTHS", description :"" },
{templateType:"Appointment Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appointment Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "TITLE", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Appointment Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_NO", description :"" },
{templateType:"Appointment Letter", keyword: "CITY", description :"" },
{templateType:"Appointment Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "HOUSE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "INITIAL", description :"" },
{templateType:"Appointment Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "NOTE", description :"" },
{templateType:"Appointment Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Appointment Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Appointment Letter", keyword: "PROBATION_MONTHS", description :"" },
{templateType:"Appointment Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appointment Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "TITLE", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Offer Letter", keyword: "CITY", description :"" },
{templateType:"Offer Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Offer Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Offer Letter", keyword: "INITIAL", description :"" },
{templateType:"Offer Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Offer Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Offer Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Offer Letter", keyword: "OFFER_DATE", description :"" },
{templateType:"Offer Letter", keyword: "OFFER_NO", description :"" },
{templateType:"Offer Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Offer Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Offer Letter", keyword: "ROLE", description :"" },
{templateType:"Offer Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Offer Letter", keyword: "STATE", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Offer Letter", keyword: "CITY", description :"" },
{templateType:"Offer Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Offer Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Offer Letter", keyword: "INITIAL", description :"" },
{templateType:"Offer Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Offer Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Offer Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Offer Letter", keyword: "OFFER_DATE", description :"" },
{templateType:"Offer Letter", keyword: "OFFER_NO", description :"" },
{templateType:"Offer Letter", keyword: "OFFERED_SALARY", description :"" },
{templateType:"Offer Letter", keyword: "PACKAGE_TYPE", description :"" },
{templateType:"Offer Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Offer Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Offer Letter", keyword: "ROLE", description :"" },
{templateType:"Offer Letter", keyword: "SALARY_IN_WORDS", description :"" },
{templateType:"Offer Letter", keyword: "SALARY_TYPE", description :"" },
{templateType:"Offer Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Offer Letter", keyword: "STATE", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Offer Letter", keyword: "CITY", description :"" },
{templateType:"Offer Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Offer Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Offer Letter", keyword: "INITIAL", description :"" },
{templateType:"Offer Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Offer Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Offer Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Offer Letter", keyword: "OFFER_DATE", description :"" },
{templateType:"Offer Letter", keyword: "OFFER_NO", description :"" },
{templateType:"Offer Letter", keyword: "OFFERED_SALARY", description :"" },
{templateType:"Offer Letter", keyword: "PACKAGE_TYPE", description :"" },
{templateType:"Offer Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Offer Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Offer Letter", keyword: "ROLE", description :"" },
{templateType:"Offer Letter", keyword: "SALARY_IN_WORDS", description :"" },
{templateType:"Offer Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Offer Letter", keyword: "SALARY_TYPE", description :"" },
{templateType:"Offer Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Offer Letter", keyword: "STATE", description :"" },
{templateType:"Relieving Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Relieving Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Relieving Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Relieving Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Relieving Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Relieving Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Relieving Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Relieving Letter", keyword: "RELIEVING_DATE", description :"" },
{templateType:"Relieving Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Relieving Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Relieving Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Relieving Letter", keyword: "TEMPLATE_TYPE", description :"" },
{templateType:"Resignation Accept", keyword: "APPROVED_DATE", description :"" },
{templateType:"Resignation Accept", keyword: "DESIGNATION", description :"" },
{templateType:"Resignation Accept", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Resignation Accept", keyword: "FIRST_NAME", description :"" },
{templateType:"Resignation Accept", keyword: "LAST_NAME", description :"" },
{templateType:"Resignation Accept", keyword: "LOCATION_NAME", description :"" },
{templateType:"Resignation Accept", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Resignation Accept", keyword: "PAY_GROUP", description :"" },
{templateType:"Resignation Accept", keyword: "REFERENCE_NO", description :"" },
{templateType:"Resignation Accept", keyword: "RESIGNATION_DATE", description :"" },
{templateType:"Resignation Accept", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Resignation Accept", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Resignation Accept", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Resignation Accept", keyword: "STATE_NAME", description :"" },
{templateType:"Resignation Accept", keyword: "TITLE", description :"" },
{templateType:"Experience Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Experience Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Experience Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Experience Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Experience Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Experience Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Experience Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Experience Letter", keyword: "RELIEVING_DATE", description :"" },
{templateType:"Experience Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Experience Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Experience Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Experience Letter", keyword: "TEMPLATE_TYPE", description :"" },
{templateType:"Appraisal Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appraisal Letter", keyword: "APPRAISAL_DATE", description :"" },
{templateType:"Appraisal Letter", keyword: "APPRAISAL_DETAIL_PARAGRAPH", description :"" },
{templateType:"Appraisal Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appraisal Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appraisal Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appraisal Letter", keyword: "LOCATION_NAME", description :"" },
{templateType:"Appraisal Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appraisal Letter", keyword: "NEXT_APPRAISAL_NOTE", description :"" },
{templateType:"Appraisal Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Appraisal Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Appraisal Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appraisal Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appraisal Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appraisal Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appraisal Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appraisal Letter", keyword: "STATE_NAME", description :"" },
{templateType:"Appraisal Letter", keyword: "TITLE", description :"" },
{templateType:"Confirmation Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Confirmation Letter", keyword: "CONFIRMATION_DATE", description :"" },
{templateType:"Confirmation Letter", keyword: "CONFIRMATION_DETAIL_PARAGRAPH", description :"" },
{templateType:"Confirmation Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Confirmation Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "LOCATION_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "NEXT_APPRAISAL_NOTE", description :"" },
{templateType:"Confirmation Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Confirmation Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Confirmation Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Confirmation Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Confirmation Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Confirmation Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Confirmation Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "STATE_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "TITLE", description :"" },
{templateType:"Retirement Extension", keyword: "DESIGNATION", description :"" },
{templateType:"Retirement Extension", keyword: "DIVISION", description :"" },
{templateType:"Retirement Extension", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Retirement Extension", keyword: "EXTENDED_FROM_DATE", description :"" },
{templateType:"Retirement Extension", keyword: "EXTENDED_TO_DATE", description :"" },
{templateType:"Retirement Extension", keyword: "FIRST_NAME", description :"" },
{templateType:"Retirement Extension", keyword: "LAST_NAME", description :"" },
{templateType:"Retirement Extension", keyword: "LOCATION", description :"" },
{templateType:"Retirement Extension", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Retirement Extension", keyword: "MONTHS", description :"" },
{templateType:"Retirement Extension", keyword: "PLANTNAME", description :"" },
{templateType:"Retirement Extension", keyword: "REFERENCE_NO", description :"" },
{templateType:"Retirement Extension", keyword: "RETIREMENT_DATE", description :"" },
{templateType:"Retirement Extension", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Retirement Extension", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Retirement Extension", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Retirement Extension", keyword: "SUBMITTED_DATE", description :"" },
{templateType:"Retirement Extension", keyword: "TITLE", description :"" },
{templateType:"Retirement Extension", keyword: "DESIGNATION", description :"" },
{templateType:"Retirement Extension", keyword: "DIVISION", description :"" },
{templateType:"Retirement Extension", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Retirement Extension", keyword: "EXTENDED_FROM_DATE", description :"" },
{templateType:"Retirement Extension", keyword: "EXTENDED_TO_DATE", description :"" },
{templateType:"Retirement Extension", keyword: "FIRST_NAME", description :"" },
{templateType:"Retirement Extension", keyword: "LAST_NAME", description :"" },
{templateType:"Retirement Extension", keyword: "LOCATION", description :"" },
{templateType:"Retirement Extension", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Retirement Extension", keyword: "MONTHS", description :"" },
{templateType:"Retirement Extension", keyword: "REFERENCE_NO", description :"" },
{templateType:"Retirement Extension", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Retirement Extension", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Retirement Extension", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Retirement Extension", keyword: "SUBMITTED_DATE", description :"" },
{templateType:"Retirement Extension", keyword: "TITLE", description :"" },
{templateType:"Recall", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Recall", keyword: "APPRAISAL_DETAIL_PARAGRAPH", description :"" },
{templateType:"Recall", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Recall", keyword: "FIRST_NAME", description :"" },
{templateType:"Recall", keyword: "INITIAL", description :"" },
{templateType:"Recall", keyword: "LAST_NAME", description :"" },
{templateType:"Recall", keyword: "LOCATION", description :"" },
{templateType:"Recall", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Recall", keyword: "RECALL_DATE", description :"" },
{templateType:"Recall", keyword: "SALARY_TABLE", description :"" },
{templateType:"Recall", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Recall", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Recall", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Recall", keyword: "TITLE", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Offer Letter", keyword: "CITY", description :"" },
{templateType:"Offer Letter", keyword: "DEPARTMENT", description :"" },
{templateType:"Offer Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Offer Letter", keyword: "INITIAL", description :"" },
{templateType:"Offer Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Offer Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Offer Letter", keyword: "LOCATION", description :"" },
{templateType:"Offer Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Offer Letter", keyword: "OFFER_DATE", description :"" },
{templateType:"Offer Letter", keyword: "OFFER_NO", description :"" },
{templateType:"Offer Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Offer Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Offer Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Offer Letter", keyword: "STATE", description :"" },
{templateType:"Offer Letter", keyword: "TITLE", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Offer Letter", keyword: "CITY", description :"" },
{templateType:"Offer Letter", keyword: "DEPARTMENT", description :"" },
{templateType:"Offer Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Offer Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Offer Letter", keyword: "INITIAL", description :"" },
{templateType:"Offer Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Offer Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Offer Letter", keyword: "LOCATION", description :"" },
{templateType:"Offer Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Offer Letter", keyword: "OFFER_DATE", description :"" },
{templateType:"Offer Letter", keyword: "OFFER_NO", description :"" },
{templateType:"Offer Letter", keyword: "OFFERED_SALARY", description :"" },
{templateType:"Offer Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Offer Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Offer Letter", keyword: "ROLE", description :"" },
{templateType:"Offer Letter", keyword: "SALARY_IN_WORDS", description :"" },
{templateType:"Offer Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Offer Letter", keyword: "STATE", description :"" },
{templateType:"Offer Letter", keyword: "TITLE", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Offer Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Offer Letter", keyword: "CITY", description :"" },
{templateType:"Offer Letter", keyword: "DEPARTMENT", description :"" },
{templateType:"Offer Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Offer Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Offer Letter", keyword: "INITIAL", description :"" },
{templateType:"Offer Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Offer Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Offer Letter", keyword: "LOCATION", description :"" },
{templateType:"Offer Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Offer Letter", keyword: "OFFER_DATE", description :"" },
{templateType:"Offer Letter", keyword: "OFFER_NO", description :"" },
{templateType:"Offer Letter", keyword: "OFFERED_SALARY", description :"" },
{templateType:"Offer Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Offer Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Offer Letter", keyword: "ROLE", description :"" },
{templateType:"Offer Letter", keyword: "SALARY_IN_WORDS", description :"" },
{templateType:"Offer Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Offer Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Offer Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Offer Letter", keyword: "STATE", description :"" },
{templateType:"Offer Letter", keyword: "TITLE", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Appointment Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "AO_LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_NO", description :"" },
{templateType:"Appointment Letter", keyword: "CITY", description :"" },
{templateType:"Appointment Letter", keyword: "DEPARTMENT", description :"" },
{templateType:"Appointment Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "HOUSE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "INITIAL", description :"" },
{templateType:"Appointment Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "NOTE", description :"" },
{templateType:"Appointment Letter", keyword: "NOTICE_PERIOD", description :"" },
{templateType:"Appointment Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Appointment Letter", keyword: "PROBATION_MONTHS", description :"" },
{templateType:"Appointment Letter", keyword: "ROLE", description :"" },
{templateType:"Appointment Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appointment Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "STATE", description :"" },
{templateType:"Appointment Letter", keyword: "TITLE", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Appointment Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "AO_LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_NO", description :"" },
{templateType:"Appointment Letter", keyword: "CITY", description :"" },
{templateType:"Appointment Letter", keyword: "DEPARTMENT", description :"" },
{templateType:"Appointment Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "HOUSE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "INITIAL", description :"" },
{templateType:"Appointment Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "NOTE", description :"" },
{templateType:"Appointment Letter", keyword: "NOTICE_PERIOD", description :"" },
{templateType:"Appointment Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Appointment Letter", keyword: "ROLE", description :"" },
{templateType:"Appointment Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appointment Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "STATE", description :"" },
{templateType:"Appointment Letter", keyword: "TITLE", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Appointment Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "AO_LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_NO", description :"" },
{templateType:"Appointment Letter", keyword: "CITY", description :"" },
{templateType:"Appointment Letter", keyword: "DEPARTMENT", description :"" },
{templateType:"Appointment Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "HOUSE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "INITIAL", description :"" },
{templateType:"Appointment Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "NOTE", description :"" },
{templateType:"Appointment Letter", keyword: "NOTICE_PERIOD", description :"" },
{templateType:"Appointment Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Appointment Letter", keyword: "PROBATION_MONTHS", description :"" },
{templateType:"Appointment Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appointment Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "STATE", description :"" },
{templateType:"Appointment Letter", keyword: "TITLE", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Appointment Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_NO", description :"" },
{templateType:"Appointment Letter", keyword: "CITY", description :"" },
{templateType:"Appointment Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "EMPLOYEE_CATEGORY", description :"" },
{templateType:"Appointment Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "HOUSE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "INITIAL", description :"" },
{templateType:"Appointment Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "NOTE", description :"" },
{templateType:"Appointment Letter", keyword: "NOTICE_PERIOD", description :"" },
{templateType:"Appointment Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Appointment Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Appointment Letter", keyword: "PROBATION_MONTHS", description :"" },
{templateType:"Appointment Letter", keyword: "ROLE", description :"" },
{templateType:"Appointment Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appointment Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "TITLE", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Appointment Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "AO_LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_NO", description :"" },
{templateType:"Appointment Letter", keyword: "CITY", description :"" },
{templateType:"Appointment Letter", keyword: "DEPARTMENT", description :"" },
{templateType:"Appointment Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "HOUSE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "INITIAL", description :"" },
{templateType:"Appointment Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "NOTE", description :"" },
{templateType:"Appointment Letter", keyword: "NOTICE_PERIOD", description :"" },
{templateType:"Appointment Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Appointment Letter", keyword: "ROLE", description :"" },
{templateType:"Appointment Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appointment Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "STATE", description :"" },
{templateType:"Appointment Letter", keyword: "TITLE", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "INITIAL", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "LOCATION", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "PAYGROUP", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "RELIEVING_DATE", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "INITIAL", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "RELIEVING_DATE", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "TEMPLATE_TYPE", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "TODAY_DATE", description :"" },
{templateType:"Experience Letter", keyword: "CURRENT_CTC", description :"" },
{templateType:"Experience Letter", keyword: "DEPARTMENT", description :"" },
{templateType:"Experience Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Experience Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Experience Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Experience Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Experience Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Experience Letter", keyword: "LOCATION_NAME", description :"" },
{templateType:"Experience Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Experience Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Experience Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Experience Letter", keyword: "RELIEVING_DATE", description :"" },
{templateType:"Experience Letter", keyword: "RESIGNATION_DATE", description :"" },
{templateType:"Experience Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Experience Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Experience Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Experience Letter", keyword: "TITLE", description :"" },
{templateType:"Resignation Accept", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Resignation Accept", keyword: "FIRST_NAME", description :"" },
{templateType:"Resignation Accept", keyword: "LAST_NAME", description :"" },
{templateType:"Resignation Accept", keyword: "LOCATION_NAME", description :"" },
{templateType:"Resignation Accept", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Resignation Accept", keyword: "PAY_GROUP", description :"" },
{templateType:"Resignation Accept", keyword: "REFERENCE_NO", description :"" },
{templateType:"Resignation Accept", keyword: "RELIEVING_DATE", description :"" },
{templateType:"Resignation Accept", keyword: "RESIGNATION_DATE", description :"" },
{templateType:"Resignation Accept", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Resignation Accept", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Resignation Accept", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Resignation Accept", keyword: "TITLE", description :"" },
{templateType:"Resignation Accept", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Resignation Accept", keyword: "FIRST_NAME", description :"" },
{templateType:"Resignation Accept", keyword: "LAST_NAME", description :"" },
{templateType:"Resignation Accept", keyword: "LOCATION_NAME", description :"" },
{templateType:"Resignation Accept", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Resignation Accept", keyword: "PAY_GROUP", description :"" },
{templateType:"Resignation Accept", keyword: "REFERENCE_NO", description :"" },
{templateType:"Resignation Accept", keyword: "RELIEVING_DATE", description :"" },
{templateType:"Resignation Accept", keyword: "RESIGNATION_DATE", description :"" },
{templateType:"Resignation Accept", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Resignation Accept", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Resignation Accept", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Resignation Accept", keyword: "TITLE", description :"" },
{templateType:"Transfer Letter", keyword: "APPROVED_DATE", description :"" },
{templateType:"Transfer Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "EFFECTIVE_DATE", description :"" },
{templateType:"Transfer Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Transfer Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_PAY_GROUP", description :"" },
{templateType:"Transfer Letter", keyword: "OLD_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "OLD_PAY_GROUP", description :"" },
{templateType:"Transfer Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Transfer Letter", keyword: "REPORTING_MANAGER", description :"" },
{templateType:"Transfer Letter", keyword: "RM_CONTACT", description :"" },
{templateType:"Transfer Letter", keyword: "RM_DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "RM_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "APPROVED_DATE", description :"" },
{templateType:"Transfer Letter", keyword: "DEPARTMENT", description :"" },
{templateType:"Transfer Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "EFFECTIVE_DATE", description :"" },
{templateType:"Transfer Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Transfer Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_DEPARTMENT", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_DESIGNATION_LINE", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_PAY_GROUP", description :"" },
{templateType:"Transfer Letter", keyword: "OLD_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "OLD_PAY_GROUP", description :"" },
{templateType:"Transfer Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Transfer Letter", keyword: "REPORTING_MANAGER", description :"" },
{templateType:"Transfer Letter", keyword: "RM_DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "RM_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "ROLE", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "TITLE", description :"" },
{templateType:"Transfer Letter", keyword: "APPROVED_DATE", description :"" },
{templateType:"Transfer Letter", keyword: "DEPARTMENT", description :"" },
{templateType:"Transfer Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "EFFECTIVE_DATE", description :"" },
{templateType:"Transfer Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Transfer Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_DEPARTMENT", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_DESIGNATION_LINE", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_PAY_GROUP", description :"" },
{templateType:"Transfer Letter", keyword: "OLD_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "OLD_PAY_GROUP", description :"" },
{templateType:"Transfer Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Transfer Letter", keyword: "REPORTING_MANAGER", description :"" },
{templateType:"Transfer Letter", keyword: "REQUEST_DATE", description :"" },
{templateType:"Transfer Letter", keyword: "RM_DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "RM_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "ROLE", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "TITLE", description :"" },
{templateType:"Transfer Letter", keyword: "APPROVED_DATE", description :"" },
{templateType:"Transfer Letter", keyword: "DEPARTMENT", description :"" },
{templateType:"Transfer Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "EFFECTIVE_DATE", description :"" },
{templateType:"Transfer Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Transfer Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_DEPARTMENT", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_DESIGNATION_LINE", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_PAY_GROUP", description :"" },
{templateType:"Transfer Letter", keyword: "OLD_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "OLD_PAY_GROUP", description :"" },
{templateType:"Transfer Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Transfer Letter", keyword: "REPORTING_MANAGER", description :"" },
{templateType:"Transfer Letter", keyword: "RM_DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "RM_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "ROLE", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "TITLE", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Appointment Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "AO_LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_NO", description :"" },
{templateType:"Appointment Letter", keyword: "CITY", description :"" },
{templateType:"Appointment Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "HOUSE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "INITIAL", description :"" },
{templateType:"Appointment Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "NOTE", description :"" },
{templateType:"Appointment Letter", keyword: "NOTICE_PERIOD", description :"" },
{templateType:"Appointment Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Appointment Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Appointment Letter", keyword: "PROBATION_MONTHS", description :"" },
{templateType:"Appointment Letter", keyword: "ROLE", description :"" },
{templateType:"Appointment Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appointment Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "STATE", description :"" },
{templateType:"Appointment Letter", keyword: "TITLE", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Appointment Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "AO_LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_NO", description :"" },
{templateType:"Appointment Letter", keyword: "CITY", description :"" },
{templateType:"Appointment Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "HOUSE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "INITIAL", description :"" },
{templateType:"Appointment Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "NOTE", description :"" },
{templateType:"Appointment Letter", keyword: "NOTICE_PERIOD", description :"" },
{templateType:"Appointment Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Appointment Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Appointment Letter", keyword: "ROLE", description :"" },
{templateType:"Appointment Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appointment Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "STATE", description :"" },
{templateType:"Appointment Letter", keyword: "TITLE", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Appointment Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "AO_LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_NO", description :"" },
{templateType:"Appointment Letter", keyword: "CITY", description :"" },
{templateType:"Appointment Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "HOUSE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "INITIAL", description :"" },
{templateType:"Appointment Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "NOTE", description :"" },
{templateType:"Appointment Letter", keyword: "NOTICE_PERIOD", description :"" },
{templateType:"Appointment Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Appointment Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Appointment Letter", keyword: "ROLE", description :"" },
{templateType:"Appointment Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appointment Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "STATE", description :"" },
{templateType:"Appointment Letter", keyword: "TITLE", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_1", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_2", description :"" },
{templateType:"Appointment Letter", keyword: "ADDRESS_LINE_3", description :"" },
{templateType:"Appointment Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "AO_LOCATION", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "APPOINTMENT_NO", description :"" },
{templateType:"Appointment Letter", keyword: "CITY", description :"" },
{templateType:"Appointment Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "HOUSE_NO", description :"" },
{templateType:"Appointment Letter", keyword: "INITIAL", description :"" },
{templateType:"Appointment Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Appointment Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "NOTE", description :"" },
{templateType:"Appointment Letter", keyword: "NOTICE_PERIOD", description :"" },
{templateType:"Appointment Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Appointment Letter", keyword: "PIN_CODE", description :"" },
{templateType:"Appointment Letter", keyword: "PROBATION_MONTHS", description :"" },
{templateType:"Appointment Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appointment Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appointment Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appointment Letter", keyword: "STATE", description :"" },
{templateType:"Appointment Letter", keyword: "TITLE", description :"" },
{templateType:"Transfer Letter", keyword: "APPROVED_DATE", description :"" },
{templateType:"Transfer Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "EFFECTIVE_DATE", description :"" },
{templateType:"Transfer Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Transfer Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_DESIGNATION_LINE", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_PAY_GROUP", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_STATE", description :"" },
{templateType:"Transfer Letter", keyword: "OLD_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "OLD_PAY_GROUP", description :"" },
{templateType:"Transfer Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Transfer Letter", keyword: "REPORTING_MANAGER", description :"" },
{templateType:"Transfer Letter", keyword: "RM_DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "RM_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "ROLE", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "TITLE", description :"" },
{templateType:"Transfer Letter", keyword: "APPROVED_DATE", description :"" },
{templateType:"Transfer Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "EFFECTIVE_DATE", description :"" },
{templateType:"Transfer Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Transfer Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_DESIGNATION_LINE", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_PAY_GROUP", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_STATE", description :"" },
{templateType:"Transfer Letter", keyword: "OLD_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "OLD_PAY_GROUP", description :"" },
{templateType:"Transfer Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Transfer Letter", keyword: "REPORTING_MANAGER", description :"" },
{templateType:"Transfer Letter", keyword: "REQUEST_DATE", description :"" },
{templateType:"Transfer Letter", keyword: "RM_DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "RM_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "ROLE", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "TITLE", description :"" },
{templateType:"Transfer Letter", keyword: "APPROVED_DATE", description :"" },
{templateType:"Transfer Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "EFFECTIVE_DATE", description :"" },
{templateType:"Transfer Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Transfer Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_DESIGNATION_LINE", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_PAY_GROUP", description :"" },
{templateType:"Transfer Letter", keyword: "NEW_STATE", description :"" },
{templateType:"Transfer Letter", keyword: "OLD_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "OLD_PAY_GROUP", description :"" },
{templateType:"Transfer Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Transfer Letter", keyword: "REPORTING_MANAGER", description :"" },
{templateType:"Transfer Letter", keyword: "RM_DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "RM_LOCATION", description :"" },
{templateType:"Transfer Letter", keyword: "ROLE", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Transfer Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Transfer Letter", keyword: "TITLE", description :"" },
{templateType:"Confirmation Letter", keyword: "CONFIRMATION_DATE", description :"" },
{templateType:"Confirmation Letter", keyword: "CONFIRMATION_DETAIL_PARAGRAPH", description :"" },
{templateType:"Confirmation Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Confirmation Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "LOCATION_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Confirmation Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Confirmation Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Confirmation Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Confirmation Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Confirmation Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "STATE_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "TITLE", description :"" },
{templateType:"Retirement Extension", keyword: "DESIGNATION", description :"" },
{templateType:"Retirement Extension", keyword: "DIVISION", description :"" },
{templateType:"Retirement Extension", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Retirement Extension", keyword: "FIRST_NAME", description :"" },
{templateType:"Retirement Extension", keyword: "LAST_NAME", description :"" },
{templateType:"Retirement Extension", keyword: "LOCATION", description :"" },
{templateType:"Retirement Extension", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Retirement Extension", keyword: "REFERENCE_NO", description :"" },
{templateType:"Retirement Extension", keyword: "RETIREMENT_AGE", description :"" },
{templateType:"Retirement Extension", keyword: "RETIREMENT_CLOSURE_DATE", description :"" },
{templateType:"Retirement Extension", keyword: "RETIREMENT_DATE", description :"" },
{templateType:"Retirement Extension", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Retirement Extension", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Retirement Extension", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Retirement Extension", keyword: "TEMPLATE_TYPE", description :"" },
{templateType:"Retirement Extension", keyword: "TITLE", description :"" },
{templateType:"Retirement Extension", keyword: "TODAY_DATE", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_CATEGORY", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_DATEOFRESIGNATION", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_DEPARTMENT", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_DESIGNATION", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_DETAILEDREASON", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_DOC", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_DOJ", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_EMPLOYMENTTYPE", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_ERELDATE", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_GRADE", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_HIGHESTQUALIFICATION", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_HOD", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_LASTDCR", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_LASTWORKINGDAY", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_LOCATION", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_NAME", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_NOTICEPERIOD", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_PAYGROUP", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_PLANT", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_REASONREL", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_RESIGNATIONSTTAUS", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_RM", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_ROLE", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_STATE", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_STATUS", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_SUBDEPARTMENT", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_TENURE", description :"" },
{templateType:"Resignation Letter", keyword: "EMPLOYEE_TOTALEXPERIENCE", description :"" },
{templateType:"Resignation Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Resignation Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Resignation Letter", keyword: "LOCATION_NAME", description :"" },
{templateType:"Resignation Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Resignation Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Resignation Letter", keyword: "RESIGNATION_DATE", description :"" },
{templateType:"Resignation Letter", keyword: "STATE_NAME", description :"" },
{templateType:"Resignation Letter", keyword: "TITLE", description :"" },
{templateType:"Confirmation Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Confirmation Letter", keyword: "CONFIRMATION_DATE", description :"" },
{templateType:"Confirmation Letter", keyword: "CONFIRMATION_DETAIL_PARAGRAPH", description :"" },
{templateType:"Confirmation Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Confirmation Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "LOCATION_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "NEXT_APPRAISAL_NOTE", description :"" },
{templateType:"Confirmation Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Confirmation Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Confirmation Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Confirmation Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Confirmation Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Confirmation Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Confirmation Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "STATE_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "TITLE", description :"" },
{templateType:"Confirmation Letter", keyword: "CONFIRMATION_DATE", description :"" },
{templateType:"Confirmation Letter", keyword: "CONFIRMATION_DETAIL_PARAGRAPH", description :"" },
{templateType:"Confirmation Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Confirmation Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "LOCATION_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Confirmation Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Confirmation Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Confirmation Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Confirmation Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Confirmation Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "STATE_NAME", description :"" },
{templateType:"Confirmation Letter", keyword: "TITLE", description :"" },
{templateType:"Appraisal Letter", keyword: "ALLOWANCE_DETAILS", description :"" },
{templateType:"Appraisal Letter", keyword: "APPRAISAL_DATE", description :"" },
{templateType:"Appraisal Letter", keyword: "APPRAISAL_DETAIL_PARAGRAPH", description :"" },
{templateType:"Appraisal Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Appraisal Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Appraisal Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Appraisal Letter", keyword: "LOCATION_NAME", description :"" },
{templateType:"Appraisal Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Appraisal Letter", keyword: "NEXT_APPRAISAL_NOTE", description :"" },
{templateType:"Appraisal Letter", keyword: "PAY_GROUP", description :"" },
{templateType:"Appraisal Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Appraisal Letter", keyword: "SALARY_TABLE", description :"" },
{templateType:"Appraisal Letter", keyword: "SECOND_SIGNATORY_DETAILS", description :"" },
{templateType:"Appraisal Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Appraisal Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Appraisal Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Appraisal Letter", keyword: "STATE_NAME", description :"" },
{templateType:"Appraisal Letter", keyword: "TITLE", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "INITIAL", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "LOCATION", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "PAYGROUP", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "RELIEVING_DATE", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Service Withdrawn Relieving Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "DESIGNATION", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "EMPLOYEE_NO", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "FIRST_NAME", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "INITIAL", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "JOINING_DATE", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "LAST_NAME", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "MIDDLE_NAME", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "REFERENCE_NO", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "RELIEVING_DATE", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "SIGNATORY_DESIGNATION", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "SIGNATORY_IMAGE", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "SIGNATORY_NAME", description :"" },
{templateType:"Service Withdrawn Experience Letter", keyword: "TODAY_DATE", description :"" },
];
  constructor(private httpService: HttpService,
    private router: Router,private util: Util) {
      currentUser: AuthData;
     }

  ngOnInit() {
 const storedUser = localStorage.getItem('currentUser');
this.currentUser = storedUser ? JSON.parse(storedUser) : null;
    this.filterModel.pageSize = 10;
    this.filterModel.templateType = "";
    this.getPrintTemplateList();
  }

  gotoPage(no){
    if( this.filterModel.pageNo == no) return;
    this.filterModel.pageNo = no;
    this.getData();    
  }

  pageSizeChange(){
    this.filterModel.pageNo = 1;    
    this.getData();    
  }
  

  getPrintTemplateList() {
    this.filterModel.pageNo = 1;    
    this.getData();  
  }

  getData(){
    this.isLoading = true;    
    this.httpService.HRpost(APIURLS.LETTER_TEMPLATE_LIST, this.filterModel).then((data: any) => {
      this.filterData = data;
     console.log(this.filterData.list);
     
      this.isLoading = false;
    }).catch((error)=> {
      this.isLoading = false;      
    }); 
  }

  AddNew()
  {
    this.isEdit = false;
    this.item ={};
    $("#detailsModal").modal("show");
  }

  EditLine(item, index){   
    this.isEdit = true; 
    this.item = Object.assign({}, item);
    this.editIndex = index;
    this.keywordsList = this.keywordsFullList.filter((x:any)=>this.item.templateType.includes(x.templateType));
    $("#detailsModal").modal("show");
  }

  create()
  {
    toastr.info("Adding...");
    this.isLoading = true;

    this.item.createdById = this.currentUser.uid;
    this.item.createdDate = this.util.getFormatedDateTime(new Date());
    this.item.modifiedById = this.currentUser.uid;
    this.item.modifiedDate = this.util.getFormatedDateTime(new Date());

    this.httpService.HRpost(APIURLS.LETTER_TEMPLATE_CREATE, this.item)
      .then((data: any) => {
        if (data == 200 || data.success) {
          toastr.success("Successfully created the template.");
          $("#detailsModal").modal("hide");
          this.getData();
          this.isEdit =false;
        }
        this.isLoading = false;
      }).catch((error)=> {
        this.isLoading = false;
        toastr.error('Error updating details...' + error);
      })
  }
  update()
  {
    toastr.info("Updating...");
    this.isLoading = true;

    this.item.modifiedById = this.currentUser.uid;
    this.item.modifiedDate = this.util.getFormatedDateTime(new Date());

    this.httpService.HRpost(APIURLS.LETTER_TEMPLATE_UPDATE, this.item)
      .then((data: any) => {
        if (data == 200 || data.success) {
          toastr.success("Successfully updated the details.");
          $("#detailsModal").modal("hide");
          this.isEdit =false;
          this.getData();
        }
        this.isLoading = false;
      }).catch((error)=> {
        this.isLoading = false;
        toastr.error('Error updating details...' + error);
      })
  }
  
  RenderMail(item){    
    this.item = Object.assign({}, item);
    $("#renderModal").modal("show");
  }


  print(): void {
 
      let printContents, popupWin, footerContent;
      printContents = document.getElementById('printable');
      //footerContent = document.getElementById('print-footer').innerHTML;
      
      const htmlContent = printContents.innerHTML;

      const blob = new Blob ([htmlContent],{ type :'text/HTML'});
      const url = window.URL.createObjectURL(blob);

      const a=document.createElement("a");
      a.href = url;
      a.download ="letter-template.html";
      a.click();
      window.URL.revokeObjectURL(url);


    }

    exportData()
    {
      this.getData();
      //$("#renderModalAll").modal("show");
      this.printmultiple();
    }

    printmultiple(): void {
 
      let printContents, popupWin, footerContent;
      printContents = document.getElementById('printableall');
      //footerContent = document.getElementById('print-footer').innerHTML;
      
      const htmlContent = printContents.innerHTML;

      const blob = new Blob ([htmlContent],{ type :'text/HTML'});
      const url = window.URL.createObjectURL(blob);

      const a=document.createElement("a");
      a.href = url;
      a.download ="letter-templates.html";
      a.click();
      window.URL.revokeObjectURL(url);


    }
}
