export interface OfficialDetails{
    appointmentOfficialDetailsId: number;
    appointmentId: number;
    employeeNo: any;
    employmentType: any;
    isConfidential: boolean;
    title: string
    firstName: string
    middleName: string
    lastName: string
    initial: string
    plantId: number;
    payGroupId: number;
    employeeCategoryId: number;
    designationId: number;
    departmentId: number;
    roleId: number;
    gradeId: number;
    grade: string
    band: string
    subDepartmentId: number;
    reportingGroupId: number;
    countryId: number;
    stateId: any;
    locationId: any;
    isMetroCity: boolean;
    correspondingAddressTypeId: number;
    dateOfJoining: any;
    noticePeriod: any;
    dateOfConfirmation: any;
    probationPeriod: any;
    reportingManagerId: number;
    reportingManagerName: string
    approvingManagerId: number;
    approvingManagerName: string
    officialEmailID: string
    isSharedEmailID: string
    roomOrBlock: string
    floor: string
    building: string
    telephoneNo: string
    extension: string
    mobileNo: string
    printTemplateId: number;
    signatoryId: number;
    aoLocation: string
    secondSignatoryId: number;
    enteredById: number;
}