export interface OfferDetails {
    offerId: number;
    offerNo: string
    isConfidential: boolean;
    pfApplicable: string
    esiApplicable: string
    epsApplicable: string
    preJoiningInitiation: string
    guid: string
    plantId: number;
    plantName: string
    payGroupId: number;
    payGroupName: string
    payGroupPrintName: string
    employeeCategoryId: number;
    employeeCategoryName: string
    title: string
    firstName: string
    middleName: string
    lastName: string
    initial: string
    gender: string
    personalEmailId: string
    mobileNo: string
    dateOfBirth: string
    age: number;
    addressLine1: string
    addressLine2: string
    addressLine3: string
    city: string
    district: string
    stateId: number;
    state: string
    pinCode: number;
    qualification: string
    locationId: number;
    location: string
    locationStateId: number;
    locationState: string
    locationStateName: string
    countryName: string
    designationId: number;
    designation: string
    grade: string
    roleId: number;
    role: string
    departmentId:number;
    department:string;
    interviewedBy: string
    assesmentReport: boolean;
    matTest: boolean;
    sendEmailNotification: boolean;
    otherEmails: string
    presentEmployer: string    
    presentDesignation: string
    salesAmount: number;
    totalExperience: number;
    presentCTC: number;
    offeredSalary: number;
    salaryType: string
    packageType: string
    referenceThru: string
    refEmployeeNo: string
    refDetails: string
    recruitmentType: string
    replacingEmployeeNumber: string
    replacingEmployeeId: number;
    replacingEmployeeName: string
    replacingEmployeePlantCode: string
    replacingEmployeePlantName: string
    replacingEmployeeDesignation: string
    replacingEmployeeDepartment: string
    replacingEmployeeCurrentCTC: number;
    replacingEmployeeDOL: string
    replacingEmployeeDOR: string
    additionalDetails: string
    status: string
    joiningDate: string
    acceptedDOJ: string
    notAcceptedReason: string
    createdDate: string
    createdById: number;
    createdByName: string
    modifiedDate: string
    modifiedById: number;
    modifiedByName: string
    emailSentDate: string    
    reportingManagerName:string;
    approvingManagerName:string;
    reportingManagerId:number;
    approvingManagerId:number;
    secondSignatoryName: string
    statusColor: string
}