export class Profile{
    constructor(
        public empId: string,
        public employeeId: string,
        public name: string,
        public designation: string,
        public email: string,
        public pcpname: string,
        public overallrating: string,
        public fiscalyear: string,
        public pcpstatus: string,
        public jobdescription: string,
        public comments: string,
        public employeeInitiated: string,
        public employeesubmittedpcp: string,
        public joining: string,
        public baselocation: string,
        public permanentaddress: string,
        public currentaddress: string,
        public personalemail: string,
        public personalphonenumber: string,
        public emgcontactname: string,
        public emgcontactnumber: string,
        public gaurdianname: string,
        public guardianrelation: string,
        public yearofexp: string,
        public relativeyearofexp: string,
        public pannuber: string,
        public visanumber: string,
        public passportnumber: string,
        public qualification: string,
        public yearofpassing: string,
        public lastcompany: string,
        public previouscompany: string,
        public competencyname: string,
        public projectname: string,
        public imgurl: string,
        public softskill: string,
        public hardskill: string,
        public reportingmangername: string,
        public reportingmangeremail: string,
        public mangername: string,
        public mangeremail: string,
        
    ){}
}