export class CodeCreationInputs{
    aland: string
    alanD1: string
    authGroup: string
    availCheck: string
    beskz: string
    bstme: string
    classNumber: string
    classType: string
    disls: string
    dismm: string
    dwerk: string
    divisionId: string
    eisbe!: number;
    ekwsl: string
    externalMatGroup: string
    ferth: string
    gewei: string
    genItemCatGroup: string
    grossWeight!: number;
    grossWeightSpecified: true;
    insmk: string
    iprkz: string
    industrySector: string
    kondm: string
    ktgrm: string
    kzech: string
    ladgr: string
    lgfsb: string
    lgort: string
    lgpro: string
    losgr: string
    locationId: string
    matnr: string
    mhdhb: string
    mtpos: string
    mvgR1: string
    mvgR2: string
    mvgR3: string
    mvgR4: string
    mvgR5: string
    materialGroupId: string
    materialLongName: string
    materialShortName: string
    materialTypeId: string
    netWeight: string
    peinh: string
    perkz: string
    plifz: string
    p_TDLINE: string
    profitCenter: string
    purchaseGroupId: string
    qmata: string
    raube: string
    rdmhd: string
    rgekz: string
    requestNo: string
    saleS_VIEW: string
    sbdkz: string
    sktof: string
    steuc: string
    stprs: string
    s_TDLINE: string
    tatyp: string
    tatyP1: string
    taxkm: string
    taxkM1: string
    tempb: string
    tragr: string
    unitOfMeasId: string
    versg: string
    vkorg: string
    vprsv: string
    vrkme: string
    vtweg: string
    valuationClass: string
    webaz: string
    xchpf: string
}